Finish [Feature]: Allow custom sounds per sender #991
monal-im/Monal pull request #1012
Opened 2024-03-06 20:50 UTC by guodong323

2024-03-07 00:29 UTC, tmolitor-stud-tu requested changes
see all my comments in code.

Furthermore your implementation does not use the configured sounds when showing notifications (you should implement this in MLNotificationManager.m)

And last but not least: setting different default sounds per account (overwritable by setting a sound per contact on that account) sounds like a sensible idea, but don't do it this way (see my first comment on AccountListController.h)

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/AccountListController.m
> +                     [[self.accountList objectAtIndex:accNo] objectForKey:@"domain"]];
Please use `var[42]` or `var[@"key"]` syntax instead of objectForKey and objectAtIndex

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactDetails.swift
> +                NavigationLink(destination: (SoundsSettingView(settings: ContactSettings(contactJid: contact.obj.contactJid)))) {
Please use our lazy closure view to make sure the sounds view is not loaded when the contact details are opened but only once the user really taps onto the sound button

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSettingsTableViewController.m
> +//                    [self performSegueWithIdentifier:@"showSounds" sender:self];
Please use our swiftUi wrappers provided in the swiftuihelpers.swift file. You can check how opening the chat background selection swiftUi view is implemented and copy that for you implementation (e.g. add an entry to the swiftuihelpers.swift file etc.)

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSettingsTableViewController.m
> +#pragma mark - Use SoundsSettingView SwiftUI
Don't implement this here, see above

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +        _selectedSound = State(initialValue: UserDefaults.standard.string(forKey: settings.contactJid + "AlertSoundFile") ?? "System Sound")
No, please don't use the standard user defaults but the global ones provided by the corresponding helpertools.m method. Otherwise you won't be able to access that value from the push app extension when pushes come in

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +                    let key = settings.contactJid + "PlaySounds"
please write a MLSoundManager.m module roughly replicating the functionality implemented in the MLImageManager.m for chat backgrounds.
(e.g. storing the sound file into a dedicated directory using a naming scheme at least consisting of the account number and lowercased jid, use MLContact instances as arguments to specify for which contact to load or save the sound file, call these functions with nil as contact to set the global sound. Don't forget to implement the cleanup function for deleting old files of deleted contacts / accounts, too,  just refer to the image manager implementation)

Maybe we want to differentiate between chat sound and call ring sound in the future, so please pick a naming scheme prefix "chat_" to reflect that.

Allow users to pick custom sounds, not just the ones packed with Monal (but allow them to choose one of the packed ones, too).

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +    let sounds = ["System Sound", "Morse", "Xylophone", "Bloop", "Bing", "Pipa", "Water", "Forest", "Echo", "Area 51", "Wood", "Chirp", "Sonar"]
don't hardcode this list but use the contents of the bundled `AlertSounds` directory to build the list.

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +            print("Error playing sound: \(error)")
Don't use `print()` but one of `DDLogError()`, `DDLogWarn()`, `DDLogInfo()`, `DDLogDebug()` or `DDLogVerbose()` to log something

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +class ContactSettings: ObservableObject {
don't use this but an instance of MLContact.

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +@objc class SoundsSettingViewController: NSObject {
don't do this here but in the swiftuihelpers.swift (see comment above)

2024-03-07 00:29 UTC, tmolitor-stud-tu commented on Monal/Classes/AccountListController.h
> +-(NSString *) getAccountNameByIndex:(NSUInteger) index;
don't do it this way, but add an entry leading to the sound settings into the XMPPEdit.m file

2024-03-07 00:35 UTC, tmolitor-stud-tu commented
One more hint: imlement MLSoundManager.m in such a way that MLContact has a field reflecting the sound settings as properties (BOOL chatSoundEnabled and NSString* chatSoundFilename) and automatically refresh these properties by issuing a `kMonalContactRefresh` and handle this refresh in `handleContactRefresh:` like already done for the contact avatar. 

Use `@StateObject ObservableKVOWrapper<MLContact>` instead of plain MLContact in swiftui to automatically react to changes of these properties.

2024-03-07 00:46 UTC, guodong323 commented on Monal/Classes/MLSettingsTableViewController.m
> +//                    [self performSegueWithIdentifier:@"showSounds" sender:self];
OK, I will check that

2024-03-07 00:48 UTC, guodong323 commented on Monal/Classes/AccountListController.h
> +-(NSString *) getAccountNameByIndex:(NSUInteger) index;
Okay, I have already see that

2024-03-07 01:04 UTC, guodong323 commented on Monal/Classes/AccountListController.h
> +-(NSString *) getAccountNameByIndex:(NSUInteger) index;
I'm a little confused by this comment, can you explain in more detail? Thank you very much!

2024-03-09 04:48 UTC, guodong323 commented
I modify it that user can upload themselves sounds

2024-03-11 21:43 UTC, tmolitor-stud-tu requested changes

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPManager.m
> +    [self upgradeObjectUserSettingsIfUnset:@"Chat_AlertSoundFile" toDefault:@"alert2"];
please upgrade this by copying the current value from `AlertSoundFile` and remove the old `AlertSoundFile` setting afterwards using `[self removeObjectUserSettingsIfSet:@"AlertSoundFile"];`

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +- (void)saveSoundData:(NSData* _Nullable)data{
please make sure your code always follows our objc coding style over here: https://github.com/monal-im/Monal/wiki/Code-style

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/AccountListController.h
> +-(NSString *) getAccountNameByIndex:(NSUInteger) index;
what do you need that method for?

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLNotificationManager.m
> +            NSInteger fileIndex = [[filename stringByReplacingOccurrencesOfString:@"alert" withString:@""] integerValue];
That's not clean. What about copying the selected sound file to the `Sound.m4a` file used for custom sounds when the user configures the sound? Then you'll only use one simple code path here.

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLNotificationManager.m
> +                content.sound = [UNNotificationSound soundNamed:@"Sound.m4a"];
How is this able to differentiate between different users aka MLContacts aka xmpp ids aka jids?

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSettingsTableViewController.m
> +                    UIViewController* soundSettingsController =[[SwiftuiInterface new] makeSoundSettings:nil];
yes, that's what I had in mind :)

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* writablePath = [self.documentsDirectory stringByAppendingPathComponent:@"Library/Sounds/"];
Use `[HelperTools getContainerURLForPathComponents:@[@"Library", @"Sounds"]]` instead of `stringByAppendingPathComponent`

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* libraryPath = [self.documentsDirectory stringByAppendingPathComponent:@"Library/Sounds/"];
don't construct this path over and over again if you already constructed it in your constructor

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* writablePath = [libraryPath stringByAppendingPathComponent:@"Sound.m4a"];
so all users have the same sound? no per-user setting of sounds anymore? that was not what I meant. I meant: per user setting of sound. And the fallback (default) sound being either settable globally or (optionally) per account.

That way I as a user would be able to globally set a sound for my work account being different from the sound on my private account. That sound could be overwritten for individual contacts if I want this.

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* libraryPath = [self.documentsDirectory stringByAppendingPathComponent:@"Library/Sounds"]; // 获取Library目录
please only use english comments

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundPickerView.swift
> +// 用于选择文档的UIViewControllerRepresentable
english comments please

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundPickerView.swift
> +                let soundURLString = MLSoundManager.sharedInstance().loadSoundURL()
only one sound for all contacts on all accounts?

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundPickerView.swift
> +            print("加载音频数据失败: \(error)")
use DDLogXXX and please log in english only

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundPickerView.swift
> +//struct SoundPickerView: View {
I won't merge pull requests containing large parts of code commented out.

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +        let pattern = "^alert(\\d+)$"
that's not clean!

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +        var contactArg:ObservableKVOWrapper<MLContact>? = nil;
don't wrap it in `ObservableKVOWrapper` here, but in the constructor of your `SoundsSettingView`

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Monal.ios.entitlements
> +	<key>com.apple.developer.usernotifications.filtering</key>
please don't commit such no-op changes in config files

2024-03-11 21:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
don't commit such changes

2024-03-12 00:10 UTC, guodong323 commented on Monal/Classes/MLSoundManager.m
> +    NSString* writablePath = [libraryPath stringByAppendingPathComponent:@"Sound.m4a"];
So I would like to confirm the current functionality, when the user sets the sound in the homepage's setting, it is setting the global sound, when the user enters the setting from the chat interface, it is setting the sound for message alerts for this contact, and if the user doesn't have a message alert sound set for a specific user, then the global sound that is set is used.

2024-03-12 00:10 UTC, guodong323 commented on Monal/Classes/MLSoundManager.m
> +    NSString* libraryPath = [self.documentsDirectory stringByAppendingPathComponent:@"Library/Sounds"]; // 获取Library目录
I will pay attention.

2024-03-13 22:26 UTC, guodong323 commented
I modify it that user can set different alert sound for different users

2024-03-14 02:13 UTC, tmolitor-stud-tu requested changes
Your solution works, but it is not clean and therefore not maintainable.
These are the reasons (some of which I already stated in a previous review, but here are all neatly listed in one place):

1. Don't comment out code unrelated to your feature, at least not in your public PR (BackgroundSettings.swift for example)
2. Don't call `MLSoundManager.sharedInstance().deleteSoundData(contact.obj)` from UI. This is not the only path leading to a deleted contact, there are many more! Use `MLXMPPManager removeContact:` instead
3. Don't set `kMonalSoundChanged` constant if you don't need it. In general: don't leave unused dead code in your public PR for me to review
4. Always stick to our coding style guidelines: https://github.com/monal-im/Monal/wiki/Code-style/
5. Don't use defaults db to save filenames. Just drop files into the `Library/Sounds` directory named appropriately. Then detect if a per-contact sound is present by checking for the presence of that file. That way even allowing sounds per-account is trivially implementable: If a per-contact file is not present, resort to the per-account file and if that isn't present, resort to a global file and if that isn't present use the default sound provided by apple (I think you get the idea). This has to be implemented in the `MLSoundManager` singleton, not in the Notification handling code. The notification handling code should just ask the sound manager to give it the appropriate sound object and then use that.
6. I appreciate you commenting your code, but don't leave non-English comments but make English comments instead.
7. Don't hardcode the builtin sounds in your SwiftUI view, but use the `MLSoundManager` to get a list of these inbuilt sounds (the sound manager can just do a directory listing to get the names of these sounds, you'll have to rename these sound files appropriately).
8. Don't do any string manipulation on builtin sound file names and instead just handle builtin sounds like you would do with external sounds: copy them over to the `Library/Sounds` directory as you would with external sounds.
9. Don't commit unrelated changes in `Monal.ios.entitlements` or `Monal.xcodeproj/project.pbxproj` (the `DEVELOPMENT_TEAM = "";` and `IPHONEOS_DEPLOYMENT_TARGET = 14.0;` changes don't belong into a public PR)

Last but not least: Please rebase your PR onto our current develop branch and squash all your commits into one, something is odd with your current PR as viewable on github and I hope this gets fixed that way (showing the diff locally is fine, though).

2024-03-17 18:59 UTC, guodong323 commented
I reset the file naming rules, but every time before selecting a new ringtone I delete the previous ringtone file, otherwise the app's memory usage will become high every time I save the file, I hope you'll be satisfied with the solution this time!

2024-03-18 23:43 UTC, tmolitor-stud-tu requested changes
Please solve *all* my comments and clean up your complete pr before asking for a new review, thanks!

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLNotificationManager.h
> +#import "MLSoundManager.h"
Please only include this in the SoundManager.m file, other users including the MLNotificationManager.h file don't need to know the definition of the SoundManager class

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLResizingTextView.m
> +    [self becomeFirstResponder];
Why is this part of a PR related to sound settings? If this is something useful, please create a new PR just for this feature.

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.h
> ++(MLSoundManager*) sharedInstance;
style!

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        NSURL* soundsDirectoryURL = [HelperTools getContainerURLForPathComponents:@[@"Library", @"Sounds"]];
yes :)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    return [NSString stringWithFormat:@"chat_%@_%@.m4a", contact.accountId.stringValue, [contact.contactJid lowercaseString]];
you don't need the `.stringValue` the `%@` format specifier will happily take an NSNumber, too :)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(NSString*) loadSoundURLForContact:(MLContact *_Nullable) contact
style!

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        userSoundKey = [NSString stringWithFormat:@"chat_global_AlertSoundFile"];
yes :)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* filename = [[HelperTools defaultsDB] objectForKey:userSoundKey];
why that? just check if there is a file named correctly in `Library/Sounds` You don't need that indirection using the defaultsDB in that design.

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        DDLogVerbose(@"No audio data is provided.");
That would be an `MLAssert`, not just a verbose logging, right?

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        DDLogDebug(@"Could not list directory contents: %@", error.localizedDescription);
that would be `DDLogError`

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        DDLogDebug(@"Could not list directory contents: %@", error.localizedDescription);
and: please log the whole error object, not just the `localizedDescription` part

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +                DDLogDebug(@"Could not delete file: %@, error: %@", file, error.localizedDescription);
same here: please log as error (or better in this case: warning) and log the whole error object.

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(void) saveSoundData:(NSData*) soundData AndWithSoundFileName:(NSString*) filename WithPrefix:(NSString*) prefix
style: the first word of a new argument label has to begin with lowercase chars.

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        userSoundKey = [NSString stringWithFormat:@"chat_%@_AlertSoundFile", [contact.contactJid lowercaseString]];
that should be the filename (sans file extension), not the defaultsdb key, right?

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        if([file hasPrefix:prefix])
Don't use prefix! take the filename, use the correct function to split off the file extension and then check if the remaining filename (without extension) matches the filename argument (again without extension)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(void) deleteSoundData:(MLContact *_Nullable) contact
style: naming: `deleteSoundDataForContact:`

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +        if([file hasPrefix:prefix])
see my comment about prefix above

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* globalSoundKey = [NSString stringWithFormat:@"chat_global_AlertSoundFile"];
unneeded indirection!

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(NSArray<NSString*>*) loadSoundFromResource
style: naming: `listBundledSounds`

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(NSArray<NSString*>*) loadSoundFromResource
(your name suggests that your function is loading sound data from some unpecified file and then returns that, only the return type gives some hint that this might not the case)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(NSString*) loadSoundURLForContact:(MLContact *_Nullable) contact
naming: this does not return an URL like specified in the method name, but an NSString* (e.g. a path): `getSoundPathForContact:`would be a much better name

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +-(NSString*) loadSoundNameForContact:(MLContact* _Nullable) contact
naming: `getSoundNameForContact:`

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSoundManager.m
> +    NSString* filename = [[HelperTools defaultsDB] objectForKey:userSoundKey];
unneeded indirection again

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPManager.m
> +    [self upgradeObjectUserSettingsIfUnset:@"chat_global_AlertSoundFile" toDefault:@"global_Xylophone.aif_Builtin"];
unneeded indirection! and also: don't destroy the proper file extension like this (hint: don't add `_Builtin`)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPManager.m
> +        [[MLSoundManager sharedInstance] deleteSoundData:contact];
yes, exactly :)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundPickerView.swift
> +            DDLogDebug("Load audio data failure: \(error)")
that's worth a DDLogError instead of DDLogDebug

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +    let sounds: [String] = MLSoundManager.sharedInstance().loadSoundFromResource()
see my comment about naming above

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Classes/SoundsSettingView.swift
> +        suffixCustom = "Custom"
why these suffixes? (unneeded indirection)

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S8D843U34Y;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S8D843U34Y;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S8D843U34Y;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S8D843U34Y;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S8D843U34Y;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +/* Begin XCLocalSwiftPackageReference section */
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +		BE71BFD02BA648910025B956 /* LibMonalRustSwiftBridge */ = {
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.ios.entitlements
> +	<true/>
don't add this to your pr

2024-03-18 23:43 UTC, tmolitor-stud-tu commented on Monal/Monal.ios.entitlements
> +	<key>com.apple.developer.usernotifications.filtering</key>
don't add this to your pr

2024-03-19 00:29 UTC, closed without merging