issue-756: Highlight selected chat in left chat list panel
monal-im/Monal pull request #1016
Opened 2024-03-12 20:51 UTC by zainashraf1562

Issue: https://github.com/monal-im/Monal/issues/756

Solved:
https://github.com/monal-im/Monal/assets/155921778/61aca67a-5b1f-498e-93cf-3143fbbeb89b

2024-03-13 20:05 UTC, tmolitor-stud-tu requested changes

2024-03-13 20:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +@property (nonatomic, strong) MLContact *selectedChat;
don't do this, but use `[MLNotificationManager sharedInstance].currentContact` (see line 575 of `ActiveChatsViewController.m` for example)

2024-03-13 20:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +@property (nonatomic, strong) MLContact *selectedChat;
Also: Please stick to our coding style guideline: https://github.com/monal-im/Monal/wiki/Code-style/

2024-03-14 21:52 UTC, zainashraf1562 commented
Update clip showing pinned chat scenario: 
https://github.com/monal-im/Monal/assets/155921778/92abc9e2-9d09-4a39-908f-4ed153575de2

Recommendation for pinned chat: Instead of using a color just include a pinned Icon into the Chat Cell. If visibility is in question you can just make the icon bigger or a brighter color to make it pop.

2024-03-16 23:02 UTC, tmolitor-stud-tu commented
> Recommendation for pinned chat: Instead of using a color just include a pinned Icon into the Chat Cell. If visibility is in question you can just make the icon bigger or a brighter color to make it pop.(issue https://github.com/monal-im/Monal/issues/755)

A Pin icon sounds good please implement that (without a solution to pinning, the highlighting of the currently visible chat is incomplete because it won't be immediately obvious if a pinned chat is currently selected or vice versa if a currently selected chat is pinned).
Pinning is currently made clear by the color of the chat list entry btw.

> Also a more intuitive way to add a chat would be to double tap it. Right now double tapping a cell is causing it to go into the first position not sure if thats on purpose or a failed attempt at pinning a chat. (Most likely reason for incorrect chat order issue https://github.com/monal-im/Monal/issues/961)

No, tapping onto a chat should only open it. it's a bug that the chat list gets sorted by this action. pinning should only be done using the appropriate button in the contact details
I don't think pinning is an action often enough executed to make a shortcut like double tapping necessary.

2024-03-21 15:54 UTC, zainashraf1562 commented
Updated clip with pinned Icon:

https://github.com/monal-im/Monal/assets/155921778/f56736a6-ff1d-45ea-87fb-85c248189039

2024-03-22 00:45 UTC, tmolitor-stud-tu commented
We are using a rebase-based workflow rather than a merge-based and sometimes force-push something into one of the top commits.

Please rebase this PR upon current develop and remove all commits not being yours by calling: `git rebase -i upstream/develop` (assuming you added the remote named "upstream" pointing to our github repo).

2024-03-23 19:19 UTC, zainashraf1562 commented
@tmolitor-stud-tu rebased.
<img width="564" alt="Screenshot 2024-03-23 at 3 18 22 PM" src="https://github.com/monal-im/Monal/assets/155921778/a643c6dc-9063-496d-8c62-84f6b1bfe815">

2024-03-25 00:12 UTC, tmolitor-stud-tu requested changes
Ah well, you did not follow our coding style guidlines in this PR, please follow our guidlines exactly: https://github.com/monal-im/Monal/wiki/Code-style/

2024-03-25 00:12 UTC, tmolitor-stud-tu commented on Monal/Classes/MLContactCell.m
> +    if (pinned) {
objc style: `{` into next line; no space between `if` and `(`, see https://github.com/monal-im/Monal/wiki/Code-style/

2024-03-25 00:12 UTC, tmolitor-stud-tu commented on Monal/Classes/MLContactCell.m
> +    if (pinned) {
here it is, please fix!

2024-03-25 00:15 UTC, tmolitor-stud-tu commented
Please also squash all commits into one and give it a commit message looking like "<your text>, fixes #756", so that the linked issue will automatically be closed...

2024-03-26 19:33 UTC, tmolitor-stud-tu commented
Please change the commit message to "Highlight selected chat, **fixes #756**"

2024-03-26 19:34 UTC, tmolitor-stud-tu requested changes
You forgot to change the commit message to something useful:
Please change the commit message to "Highlight selected chat, **fixes #756**"

2024-03-27 00:27 UTC, tmolitor-stud-tu approved these changes
You still did not follow our coding guidlines!
I will merge this nevertheless, but I don't want to have myself repeat here in the future

2024-03-27 00:27 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    if ([MLNotificationManager sharedInstance].currentContact != nil && [chatContact isEqual:[MLNotificationManager sharedInstance].currentContact]) {
You still did not follow our coding guidlines!
I will merge this nevertheless, but I don't want to have myself repeat here in the future

2024-03-27 00:27 UTC, merged