Rewrite debug menu using SwiftUI, Issue-990
monal-im/Monal pull request #1027
Opened 2024-03-29 19:57 UTC by zainashraf1562

issue: #990 
Video Clip:
https://github.com/monal-im/Monal/assets/155921778/3e892bc4-8090-40b5-b2aa-245441a0c690

2024-03-30 07:53 UTC, tmolitor-stud-tu requested changes

2024-03-30 07:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +    @State private var logUDPHostname: String = ""
Please use the appropriate property wrapper to automatically read and write from/to the defaults db, like done over here: https://github.com/monal-im/Monal/blob/develop/Monal/Classes/PrivacySettings.swift#L43

(you probably don't need an extra object to pack all these vars into, though)

2024-03-30 07:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        .overlay(
Please use our [Loading Overlay](https://github.com/monal-im/Monal/blob/develop/Monal/Classes/LoadingOverlay.swift) instead of `.overlay` and `ProgressHUD` (we want to ditch `ProgressHUD` once everything is ported to swiftui).

2024-03-30 07:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        .onDisappear(perform: {
You can ditch the complete `onDisappear` invocation once you migrated all your defaults db vars using the appropriate `@defaultsDB` property wrapper.

2024-03-30 07:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            if logUDPSwitch, let sortedLogFileInfos = HelperTools.fileLogger?.logFileManager.sortedLogFileInfos,let firstLogFileInfo = sortedLogFileInfos.first {
Don't check for `logUDPSwitch` here. That switch has nothing to do with whether the logfiles are accessible or not.

Besides that: the idea is to let the user not just access the newest logfile (like the old ui did), but also every other logfile listed in `sortedLogFileInfos`.

2024-03-30 07:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                do {
Don't try to load logfiles into memory. That's not possible and this "Only shareable for now" is an old artifact of the old UI from 2020 where the log could be displayed directly in the UI.

We don't want that now and it isn't even possible because logfiles are binary now.

2024-03-30 07:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            HStack {
Didn't we talk about a tabbed layout having these tabs?

1. A tab listing all logfiles being able to export them by tapping onto them. This tab should also list the database file to export it. (A simple list of filenames would be enough to distinguish logfiles and database files)
2. A tab for configuring the udp logger
3. A tab for inducing several different crashes, to test crash reporting and logging etc.

2024-03-30 21:17 UTC, zainashraf1562 commented
Update Video Clip:
https://github.com/monal-im/Monal/assets/155921778/e70ae13f-7bfb-4b6f-bb53-5aac95990705

2024-04-01 08:49 UTC, tmolitor-stud-tu requested changes

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                    Text(logFileInfo.fileName)
Why do you use `Text()` instead of `Button()`?

Why not:

```
Button(logFileInfo.fileName) {
    fileURL = URL(fileURLWithPath: logFileInfo.filePath)
} 
```

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        .sheet(isPresented: $showShareSheet, onDismiss: {
This can be shortened to:

```
.sheet(isPresented:$showShareSheet) {
    if let fileURL = fileURL {
        ActivityViewController(activityItems: [fileURL])
    }
}
```

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            showShareSheet=false
You don't need to set that to false, the `.sheet()` implementation will already do this for you.

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        .onChange(of: fileURL) { newValue in
Why not write a generic binding that projects an optional value to a boolean?
That way you could ditch the `.onChange` and instead use this binding and the optional `fileURL` to set the `isPresented:` of the sheet.

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +class LogDefaultDB: ObservableObject {
Why did you use this additional class? Couldn't you set the `@defaultsDB("udpLoggerEnabled") var udpLoggerEnabled:Bool` on the `UDPConfigView` itself?

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                Toggle("", isOn: $defaultDB.udpLoggerEnabled)
why not label this toggle?

In general: wouldn't a layout having all these fields listed one per line and having a proper label on them look nicer and easier to understand (hint: `Form`)?

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                    .foregroundColor(.red)
Why not set the foreground color onto the whole `VStack` instead of every individual `Text`?

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                Text("Runtime Crash")
That's not "runtime crash" but "Try to call unknown handler method".

All these crashes are runtime crashes, strictly speaking ;)

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                showLoadingOverlay(overlay, headline: NSLocalizedString("Reconnecting", comment: "Will logout and reconnect any connected accounts."))
you don't need `NSLocalizedString` here, `showLoadingOverlay` takes a `StringProtocol` string which will be automatically translatable.

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                showLoadingOverlay(overlay, headline: NSLocalizedString("Reconnecting", comment: "Will logout and reconnect any connected accounts."))
Do you want the comment to be visible on screen? Or is that comment meant for translators?

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            Button("Reconnect All", action: {
A more swiftui-ish way of writing this would be:

```
Button("Reconnect All") {
    isReconnecting = true
    [...]
}
```

2024-04-01 08:49 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            Spacer()
don't space them out evenly. on bigger screens that looks rather ugly. use a spacer with a hardcoded size instead and add a dynamic `Spacer()` as last item of your `VStack` to cover the remaining height of the view.

2024-04-02 17:49 UTC, zainashraf1562 commented on Monal/Classes/LogView.swift
> +                    Text(logFileInfo.fileName)
The idea in my mind was to have it similar to a tableview as a list of buttons just seems a bit weird UI wise.

2024-04-02 17:55 UTC, zainashraf1562 commented on Monal/Classes/LogView.swift
> +        .onChange(of: fileURL) { newValue in
i had that initially but the view was loading empty the first time we loaded a sharesheet. when i waited for logurl to change before sharing it loaded properly. I made the assumption it was because of some background task while retrieving the url for first time that cause sharesheet to show before url was set but ill look into it again.

2024-04-02 18:19 UTC, zainashraf1562 commented on Monal/Classes/LogView.swift
> +class LogDefaultDB: ObservableObject {
well @defaultsDB in not a Binding Value and directly making it binding by using @state has various complexities like now you have a binding<defaultsDB<String>> instead of expexted  binding<String>. So unless we change @defaultsDB to be binding in itself encapsulating the values under a class and using ObservableObject seems to be the best alternative at least from my trails.

2024-04-21 22:10 UTC, tmolitor-stud-tu requested changes
Sorry for the long delay, I was on vacation and just recently got up to speed again.

There are still some comments open, please fix them.

2024-04-21 22:10 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +import SwiftUI
you don't need to import `SwiftUI` nor do you need to import `monalxmpp`, these are already imported globally in `SwiftuiHelpers.swift`

2024-04-21 22:10 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                    Text(logFileInfo.fileName)
Normal clickable text in swiftui should be a button to allow blind people to use the accessibility tools of iOS. For not visually impaired people a `Text()` or `Button()` makes no visual difference.

2024-04-21 22:10 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +class LogDefaultDB: ObservableObject {
Okay, good point :)

2024-04-21 22:10 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +import SwiftUI
This seems still pending?

2024-04-21 22:10 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +import monalxmpp
You don't need to import this either.

2024-04-21 22:10 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +struct ActivityViewController: UIViewControllerRepresentable {
Nice that you put this into `SwiftuiHelpers.swift` to be reusable :)

2024-04-21 22:53 UTC, tmolitor-stud-tu approved these changes
I've changed various things myself and now it can be merged.

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +import SwiftUI
```suggestion
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +import monalxmpp
```suggestion
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                        }
```suggestion
                    Button(logFileInfo.fileName) {
                        fileURL = URL(fileURLWithPath: logFileInfo.filePath)
                    }
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                        }
```suggestion
                    Button(dbFileURL.lastPathComponent) {
                        self.fileURL=dbFileURL
                    }
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                self.sortedLogFileInfos=sortedLogFileInfos
```suggestion
                self.sortedLogFileInfos = sortedLogFileInfos
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            })
```suggestion
            Button("Try to call unknown handler method") {
                DispatchQueue.global(qos: .default).async(execute: {
                    HelperTools.flushLogs(withTimeout: 0.100)
                    let handler = MLHandler(delegate: self, handlerName: "IDontKnowThis", andBoundArguments: [:])
                    handler.call(withArguments: nil)
                })
            }
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            })
```suggestion
            Button("Bad Access Crash") {
                HelperTools.flushLogs(withTimeout: 0.100)
                let delegate: AnyClass? = NSClassFromString("MonalAppDelegate")
                print(delegate.unsafelyUnwrapped.audiovisualTypes())
                
            }
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            })
```suggestion
            Button("Assertion Crash") {
                HelperTools.flushLogs(withTimeout: 0.100)
                assert(false)
            }
            Button("Fatal Error Crash") {
                HelperTools.flushLogs(withTimeout: 0.100)
                fatalError("fatalError_example")
            }
            Button("Nil Crash") {
                HelperTools.flushLogs(withTimeout: 0.100)
                let crasher:Int? = nil
                print(crasher!)
            }
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                    Text("UDP Config")
```suggestion
                    Text("UDP Logger")
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        })
```suggestion
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        .onChange(of:isReconnecting) { _ in
```suggestion
        .onChange(of: isReconnecting) { _ in
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +                showLoadingOverlay(overlay, headline: "Reconnecting", description: "Will logout and reconnect any connected accounts.")
```suggestion
                showLoadingOverlay(overlay, headline: "Reconnecting", description: "Will log out and reconnect all (connected) accounts.")
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +            else{
```suggestion
            } else {
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +        LogView()
```suggestion
        DebugView()
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +}
```suggestion
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +class LogDefaultDB: ObservableObject {
```suggestion
class DebugDefaultDB: ObservableObject {
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +    @ObservedObject var defaultDB: LogDefaultDB
```suggestion
    @ObservedObject var defaultDB: DebugDefaultDB
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/LogView.swift
> +struct LogView: View {
```suggestion
struct DebugView: View {
```

2024-04-21 22:53 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +
```suggestion

extension Binding where Value == Bool {
  static func mappedTo<Wrapped>(bindingToOptional: Binding<Wrapped?>) -> Binding<Bool> {
    Binding<Bool>(
      get: { bindingToOptional.wrappedValue != nil },
      set: { newValue in if !newValue { bindingToOptional.wrappedValue = nil } }
    )
  }
}

```

2024-04-21 22:56 UTC, merged

2024-04-21 23:24 UTC, tmolitor-stud-tu commented
I've fixed some more stuff, see here: https://github.com/monal-im/Monal/commit/1c0ad61aa9e6fc6a155c1073b5a2f178dac94f99

2024-04-22 00:52 UTC, zainashraf1562 commented on Monal/Classes/LogView.swift
> +                    Text(logFileInfo.fileName)
Ahh, that's a perspective I overlooked. Thanks for shedding light on it.

2024-04-22 01:04 UTC, zainashraf1562 commented on Monal/Classes/LogView.swift
> +                        }
Seems like i do make the error of replacing button with clickable text. Noted :)

2024-04-22 01:22 UTC, zainashraf1562 commented on Monal/Classes/LogView.swift
> +import SwiftUI
Ah for some reason it showed as outdated so it slipped my radar.