highlighted chat user visibility, fixes #1026
monal-im/Monal pull request #1031
Opened 2024-04-02 19:35 UTC by zainashraf1562

issue #1026 
Video Clip:
https://github.com/monal-im/Monal/assets/155921778/58234894-04a3-4bee-97af-067c13956181

2024-04-02 19:37 UTC, zainashraf1562 commented
Also another bug i just noticed for the Me we don't have ":" to separate from last message.

2024-04-21 22:17 UTC, tmolitor-stud-tu requested changes
Please apply my suggestions to fix the style according to our coding style guide in our wiki.

2024-04-21 22:17 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    else{
```suggestion
    else
    {
```

2024-04-21 22:17 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    if([MLNotificationManager sharedInstance].currentContact != nil && [chatContact isEqual:[MLNotificationManager sharedInstance].currentContact]){
```suggestion
    if([MLNotificationManager sharedInstance].currentContact != nil && [chatContact isEqual:[MLNotificationManager sharedInstance].currentContact])
```

2024-04-21 22:17 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    }
```suggestion
```

2024-04-21 22:22 UTC, merged

2024-04-21 22:24 UTC, tmolitor-stud-tu commented
I've changed the style myself and merged it, see here: https://github.com/monal-im/Monal/commit/98a5aac201f095917d48ebaac211c811da0ff5ea

2024-04-22 01:15 UTC, zainashraf1562 commented
> Please apply my suggestions to fix the style according to our coding style guide in our wiki.
Ah Apologies creature of habit 😭 will be more mindful in future.