Monal Onboarding
monal-im/Monal pull request #1083
Opened 2024-06-16 23:46 UTC by thevaidik

Adding initial onboarding in Monal

2024-06-17 06:56 UTC, licaon-kter commented
Pics? :)

2024-06-17 16:37 UTC, thevaidik commented
There are some final changes to be made, I'll post it as soon as it's done

2024-06-27 01:40 UTC, tmolitor-stud-tu reviewed
Please fix

2024-06-27 01:40 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +    @defaultsDB("AutodeleteAllMessagesAfter3Days")
This setting does not exist anymore. That's the reason it crashes for you. Check out the PrivacySettings view in GeneralSettings.swift.

2024-06-27 01:40 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                       hasToggle: false,
Don't do this! Use the original views as defined in GeneralSettings.swift.

If you want to only show a subset of settings, change GeneralSettings.swift and make its views accept some argument in their constructor to hide/show settings (maybe name it `onboardingActive` and wrap all settings you don't want to show in an `if !onboardingActive`.

Duplicated code is not maintainable and I won't merge duplicated code.

2024-06-27 01:40 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                                Button(action: {
Only show a login/signup button if no account was yet created, replace the button with a simple close button otherwise

2024-06-27 01:40 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +        _ = AddTopLevelNavigation(withDelegate: delegate, to: welcomeLogInView)
That line is a no-op

2024-06-27 01:40 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +                navigateToWelcomeLogIn(with: delegate)
Don't do this, just leave the WelcomeLogin stuff as it was

2024-06-27 01:40 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +        UIViewController* loginViewController = [[SwiftuiInterface new] makeViewWithName:@"OnboardingView"];
No, the onboarding flow should only be displayed if not yet displayed (add a user defaults setting for that (don't forget to set a default value for that setting in `MLXMPPManager.m`).

If the onboarding flow should NOT be displayed (it was already since app install) AND we don't have any enabled account, then show the welcome login view (read: use an if - else if construct here)

2024-06-27 19:45 UTC, thevaidik commented
> Pics? :)
Here are some
<img width="304" alt="Screenshot 2024-06-28 at 01 04 01" src="https://github.com/monal-im/Monal/assets/106925209/79c28c76-cba2-4a18-9ca
<img width="304" alt="Screenshot 2024-06-28 at 01 04 08" src="https://github.com/monal-im/Monal/assets/106925209/354be4ed-024f-4a61-bda5-c7a59a79b533">
3-403c2a5f5648">

2024-06-27 19:47 UTC, thevaidik commented on Monal/Classes/BoardingCards.swift
> +                                Button(action: {
Done !

2024-06-28 01:57 UTC, tmolitor-stud-tu requested changes
Please test the onboarding flow in the catalyst build on macOS and share some screenshots.

2024-06-28 01:57 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    else if([[DataLayer sharedInstance] enabledAccountCnts].intValue == 0)
you don't need a `else if`, if you use return above ;) (no blocker, just something I wanted to mention)

2024-06-28 01:57 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +            .foregroundColor(.black)
I bet this one would not be visible in dark mode, please check that

2024-06-28 01:57 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                       customView: AnyView(GeneralSettings())
I already wrote that in my last review:
Don't show the whole General Settings stuff.
The curated list of settings you had earlier was way better.

--> Use one or even more cards to show these curated settings --> use `PrivacySettings`view on one card for example, not the umbrella `GeneralSettings` --> Use something like `GeneralSettings(onboardingActive: true)` to show only these curated settings change the code in `GeneralSettings.swift` to define what is part of this curated list.

2024-06-28 01:57 UTC, tmolitor-stud-tu commented on Monal/Classes/GeneralSettings.swift
> +    var hasSeenPrivacySettings: Bool
Why add a space at the end of that line? Please remove that.

2024-06-28 01:57 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +    @objc(makeOnboardingScreenForPresentation)
Don't rename functions to be differently in objc and swift if you don't have to.
Just name it `makeOnboardingScreenForPresentation` in swift, too.

2024-06-28 01:57 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +            case "OnboardingView" :
Don't add these, if you don't use it (you are using `makeOnboardingScreenForPresentation` above, right?).

2024-06-28 02:00 UTC, tmolitor-stud-tu requested changes
Some more stuff to change

2024-06-28 02:00 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +private func dismissOnboarding() {
This is what the sheet dismisser is for, that's used in almost all other swiftui views. Use that, too!

2024-06-29 00:33 UTC, thevaidik commented on Monal/Classes/GeneralSettings.swift
> +    var hasSeenPrivacySettings: Bool
space where? everything seems same 🤔

2024-07-02 23:13 UTC, tmolitor-stud-tu requested changes
Please fix all these comments and ACK THEM by answering each of them.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    if(![[HelperTools defaultsDB] boolForKey:@"HasCompletedOnboarding"])
please name new defaultsDB entries beginning with a lowercase letter (just like you would do with properties). I wan't to migrate away from the current mess of some defaultsDB entries being lowercase and others being uppercase.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/ActiveChatsViewController.m
> +    else if([[DataLayer sharedInstance] enabledAccountCnts].intValue == 0)
Did you see this?

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                       articleText: """
All these text must either be made translatable by directly putting them into a `Text()` view (without any indirection through a variable). For example by making the `description` and `articleText` etc. fields of type `Text` instead of type `String`.

Or by using `NSLocalizedString("text", comment:"")` around the text. For readability and flexibility I'd prefer the first, though.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                                        .font(.custom("MarkerFelt-Wide", size: 80))
Where does this font come from? I don't see that font anywhere in this PR. What license does it have?

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +            .font(.custom("HelveticaNeue-Medium", size: 20))
Where does this font come from? I don't see that font anywhere in this PR. What license does it have?

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +    let cards: [OnboardingCard] = [
Instead of having the definition of our `OnboardingCard`s inside the `OnboardingView`, a better approach would be to write a view builder function returning a `OnboardingView` and supplying the cards in the call to constructor of the `OnboardingView`.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +struct CustomTextView: View {
Make this a simple function taking a `Text` view and returning a view with modified font and color. See the comment about translatability.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                            }
Don't check for nil and use a forced unwrap, but use an `if let` construct!

```suggestion
                            if let articleText = cards[index].articleText {
                                CustomTextView(text: articleText)
                                    .multilineTextAlignment(.leading)
                            }
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +                                    .frame(minWidth: 350, maxWidth: .infinity, minHeight: 600, maxHeight: .infinity)
I don't like these fixed sizes. If you can't get rid of them, I'll try myself after merging this.

Fixed sizes will make the UI look ugly if the translated text is shorter than the original english one or if the phone uses a different text size than the standard one.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +            .frame(width: 350, height: 770)
I don't like fixed sizes!

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +            onboardingState.hasCompletedOnboarding = true
Don't set this when showing the onboarding, but when the user completed it and presses the Close button.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +
Why that many empty lines at the end?

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/GeneralSettings.swift
> +    var hasSeenPrivacySettings: Bool
That space:

```suggestion
    var hasSeenPrivacySettings: Bool
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/GeneralSettings.swift
> +                Section(header: Text("Settings you should check out !")) {
That text should ideally be inside the `OnboardingView` (as part of the card title, description etc.), not inside `PrivacySettingsOnboarding`.

If you can't solve that, I'll do it myself after the merge.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +            host.rootView = AnyView(AddTopLevelNavigation(withDelegate: delegate, to: PrivacySettings()))
Don't randomly remove spaces!

```suggestion
                host.rootView = AnyView(AddTopLevelNavigation(withDelegate: delegate, to: PrivacySettings()))
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 7RWMCRQ389;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 7RWMCRQ389;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 7RWMCRQ389;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 7RWMCRQ389;
Don't add random xcode stuff to the project file not related to your PR, use `git add -p`!

```suggestion
```

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +    func makeOnboardingScreenForPresentation() -> UIViewController {
Don't write an extra function, but add this as a new case to `makeView` of the `SwiftuiInterface`class.

2024-07-02 23:13 UTC, tmolitor-stud-tu commented on Monal/Classes/BoardingCards.swift
> +import FrameUp
I asked you to import `FrameUp` to use its `SmartScrollView`, not for the sake of importing it ;)

2024-07-06 12:58 UTC, tmolitor-stud-tu approved these changes

2024-07-06 12:59 UTC, merged