Implement dynamic UI updates for OMEMO device updates
monal-im/Monal pull request #1105
Opened 2024-07-12 23:23 UTC by matthewrfennell

This PR only addresses new / removed devices, and is the first part of #1101

I show the group chat view, as this is the most complex case. The "own keys" view works similarly.

https://github.com/user-attachments/assets/3c631e27-a3c7-4e84-9cd5-36961d5ab071

I removed the explicit delete action, as this is now handled by refreshing the keys. To check it still works:

https://github.com/user-attachments/assets/16cd8aac-b755-467c-8d5b-7b46533c5ff8

Even after this change, I noticed some cases where the device list does not update after creating a device (on other accounts - not the user's own account). However, these all turned out to be differences between Monal's view and the server's view, instead of mismatches between the view and Monal's own DB.

Still to do (in future PR's, if it's ok to merge this as-is):
* show added / removed users
* show changes in trust
* investigate above cases where Monal and server are out of sync (probably because server did not send the update message to Monal?)
* add animation to delete button

2024-07-14 10:07 UTC, tmolitor-stud-tu requested changes
some really small changes, everything else looks quite good! :)

after these changes it'll be okay to merge this as is, but I'm still keen to see a rawlog (recorded using the udp log receiver) of the sync issue :)

2024-07-14 10:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLOMEMO.m
> +    [self notifyKnownDevicesUpdated:source];
this should be in an else to not trigger the notification twice for own devicelist updates

2024-07-14 10:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLConstants.h
> +#define kMonalKnownDevicesUpdated @"kMonalKnownDevicesUpdated"
since this is used for every omemo update, maybe use this name

```suggestion
#define kMonalOmemoStateUpdated @"kMonalOmemoStateUpdated"
```

2024-07-14 21:57 UTC, matthewrfennell commented on Monal/Classes/MLOMEMO.m
> +    [self notifyKnownDevicesUpdated:source];
Thanks for catching this!
I've done it a slightly different way - removing the call from `handleOwnDevicelistUpdate` since it is only called from here. Hopefully ok, but let me know what you think :)

2024-07-14 22:45 UTC, tmolitor-stud-tu requested changes

2024-07-14 22:45 UTC, tmolitor-stud-tu commented on Monal/Classes/MLOMEMO.m
> +    [self notifyKnownDevicesUpdated:source];
while removing the call to `notifyKnownDevicesUpdated` from `handleOwnDevicelistUpdate` seems fine at first glance, having it in the `handleOwnDevicelistUpdate` could be beneficial if this method is called from somewhere else, too (in the future)...so I'd rather use an if at the call site (`processOMEMODevices:from:`) rather than removing the call to `notifyKnownDevicesUpdated` from `handleOwnDevicelistUpdate`....

2024-07-15 22:30 UTC, matthewrfennell commented on Monal/Classes/MLOMEMO.m
> +    [self notifyKnownDevicesUpdated:source];
That's fair. Thanks for the re-review!

2024-07-19 00:55 UTC, tmolitor-stud-tu approved these changes
Great! :)

2024-07-19 00:55 UTC, merged