Updating calls that are deprecated in iOS 16
monal-im/Monal pull request #1112
Opened 2024-07-20 08:59 UTC by matthewrfennell

2024-07-20 18:44 UTC, tmolitor-stud-tu commented
No need to do this step by step while maintaining compilability. Its okay to temporarily break things by bumping the minimum version and then fix them step by step until it compiles again :)

2024-07-20 19:29 UTC, tmolitor-stud-tu requested changes

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> -                    return [/*"profile"*/] + reinviteEntry + ["owner", "admin", "member", "outcast"]
this comment should be left there because it was intentional. but of course it can be changed to `/*["profile"] +*/`

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> -                    return [/*"profile"*/] + reinviteEntry + ["owner", "admin", "member", "outcast"]
same for the other /*profile*/ parts of course

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> -                if newAffiliation == "profile" {
please keep that, too

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> -                                NavigationLink(destination: LazyClosureView(ContactDetails(delegate:SheetDismisserProtocol(), contact:contact)), tag:contact, selection:$navigationActive) { EmptyView(
and this, to keep the profile navigation intact

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> -    @State private var navigationActive: ObservableKVOWrapper<MLContact>?
after reviewing the complete file: please keep everything as is, the "profile" stuff was intentionally kept in to be able to uncomment it later on if needed

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/RegisterAccount.swift
> +        if #available(iOS 16.0, *) {
just do it the ios 16 way, we'll do a hard cut...that's easier :)

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/RegisterAccount.swift
> +    private func termsSiteForCurrentLanguage() -> URL {
good idea to put that into an extra func! :)

2024-07-20 19:29 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> -        } else if affiliation == "profile" {
please keep that in, too (same for the "profile" stuff below=

2024-07-20 21:09 UTC, matthewrfennell commented on Monal/Classes/MemberList.swift
> -                                NavigationLink(destination: LazyClosureView(ContactDetails(delegate:SheetDismisserProtocol(), contact:contact)), tag:contact, selection:$navigationActive) { EmptyView(
This was the change that triggered all the deletions; this format of `NavigationLink(destination:tag:selection)` is [deprecated now](https://developer.apple.com/documentation/swiftui/navigationlink/init(_:destination:tag:selection:)-8ohtn) in iOS 16.

Should I comment it out for now or leave as-is? It won't compile for the time being until we change it.

2024-07-20 21:16 UTC, matthewrfennell commented on Monal/Classes/MemberList.swift
> -    @State private var navigationActive: ObservableKVOWrapper<MLContact>?
Ah ok, thanks for the heads up! I know to check first next time :)

2024-07-21 01:14 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> -                                NavigationLink(destination: LazyClosureView(ContactDetails(delegate:SheetDismisserProtocol(), contact:contact)), tag:contact, selection:$navigationActive) { EmptyView(
The proper solution would be to use a `NavigationStack` instead of a `NavigationView` in `AddTopLevelNavigation` (located at `SwiftuiHelpers.swift`) alongside the `init(_:value:)` of `NavigationLink` and `navigationDestination(for:destination:)`.

2024-07-26 04:14 UTC, tmolitor-stud-tu approved these changes
Since my requested changes are only small, I'll merge this and do them myself afterwards to not delay this further :)

Thanks for your contribution!

2024-07-26 04:14 UTC, tmolitor-stud-tu commented on Monal/Classes/Quicksy_RegisterAccount.swift
> +    rq.addValue(Locale.current.language.languageCode?.identifier ?? "en", forHTTPHeaderField: "Accept-Language")
why not use the `DEFAULT_REGION_CODE` here, too?

2024-07-26 04:14 UTC, tmolitor-stud-tu commented on Monal/Classes/Quicksy_RegisterAccount.swift
> +                    print("######## \(String(describing:regionCode))")
oh, that's my fault, the `print` statements in here were just for debugging, you can safely remove them :)

2024-07-26 04:14 UTC, merged