Minor BugFixes
monal-im/Monal pull request #1157
Opened 2024-07-30 18:20 UTC by NafSyed

The following are the changes :)

-> Added a function to properly handle the reconnect Manager in the **DebugView** as it was throwing an error and couldn't know where to place the function correctly.

-> Added Initializers to the connectedAccount, selectedAccount, and preAuthToken because they were not initialized and were throwing errors in **AddContactMenu**.

-> Added the Initializer to the needingMigration variable in the **PasswordMigration**

2024-07-30 23:46 UTC, tmolitor-stud-tu requested changes
While I appreciate you trying to give something back, this PR is either fixes for non-issues or nonsense like changing the team ID.

2024-07-30 23:46 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +    @State private var connectedAccounts: [xmpp] = []
This is not needed as these variables are initialized in the constructor of that struct: line 44, 51, 52

2024-07-30 23:46 UTC, tmolitor-stud-tu commented on Monal/Classes/DebugView.swift
> -                MLXMPPManager.sharedInstance().reconnectAll()
This never throwed an error

2024-07-30 23:46 UTC, tmolitor-stud-tu commented on Monal/Classes/DebugView.swift
> +func reconnectAll() -> Promise<Void> {
The delay is purely to give some feedback to the user (more precice: normally I, because this is the debug menu mainly intended for me to test things) that they did not miss the mark when tapping onto that button.

There is no need to delay that even further. And even if one would: `asyncAfter` with `seal.fulfill(())` is the wrong way to do it, use the PromiseKit `after()` in combination with `then(on:)` or PromiseKit's `DispatchQueue` extension `DispatchQueue.global().async(.promise) {}`

2024-07-30 23:46 UTC, tmolitor-stud-tu commented on Monal/Classes/PasswordMigration.swift
> +    @State var needingMigration: [Int:[String:NSObject]] = [:]
Same here, already initialized in line 26

2024-07-30 23:46 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +		D1B192C62C595F8C008F3155 /* LibMonalRustSwiftBridge in Frameworks */ = {isa = PBXBuildFile; productRef = D1B192C52C595F8C008F3155 /* LibMonalRustSwiftBridge */; };
Why did you add all these rust things all over the place? The rust lib was included just fine before, no need to add more of it. You added it either to targets that already had the lib included, or to targets not using this lib at all (the lib is only used by the monalxmpp target).

2024-07-30 23:46 UTC, tmolitor-stud-tu commented on Monal/Monal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 93J5WL8H3Z;
Why did you change our team id? Even if the rest of this PR included things I could merge, that one would prevent it. Merging this will block me from uploading updates to the appstore unless I change it back to our id.

2024-07-30 23:46 UTC, closed without merging

2024-07-31 03:10 UTC, NafSyed commented
Hey, I hear you about the changes to the TeamID I think I unfortunately might have done it, and my sincere apologies for that!!

But I got the errors that's why I made the changes

<img width="722" alt="Screenshot 2024-07-31 at 8 32 27 AM" src="https://github.com/user-attachments/assets/b22540a2-fe57-4bce-b829-ee7815ef61cb">

<img width="719" alt="Screenshot 2024-07-31 at 8 33 46 AM" src="https://github.com/user-attachments/assets/4862eae0-ffcc-47da-ba3b-7c8de02c03e1">


Could you explain why this happened so, that I can understand it might not happen later

2024-07-31 05:02 UTC, tmolitor-stud-tu commented
That's simply because you messed with the code, possibly removing `@State` on these vars or commenting out something vital.

Monal just compiles fine over here, otherwise I would not be able to publish updates in the appstore ;)

> Could you explain why this happened so, that I can understand it might not happen later

Pro tip: when something stops working, roll back your changes step by step until it works again. That last step is possibly where everything gone wrong.

2024-07-31 05:03 UTC, tmolitor-stud-tu commented
Hint about reconnectAll(): that method does not return a promise, so you can't use it as such ;)

2024-07-31 05:07 UTC, tmolitor-stud-tu commented
Why did you change all those lines of code anyway?

2024-07-31 05:07 UTC, NafSyed commented
Fine, I think I'll delete the project and will try to download it once again so that everything works properly :) and I'm sorry if I messed up something it was not my intention as it was my first time doing an OSC, can't wait to work with you on the features.

2024-07-31 05:09 UTC, NafSyed commented
> Why did you change all those lines of code anyway?

I didn't change any code as they were throwing an error the moment I cloned it from GitHub. That's why I changed them to silence the error

2024-07-31 05:51 UTC, tmolitor-stud-tu commented
https://github.com/monal-im/Monal/wiki/Building-Monal

2024-07-31 11:00 UTC, NafSyed commented
Hey, I've re-downloaded the project and I got one error, I didn't make any changes nor I messed up with the code 

<img width="1440" alt="Screenshot 2024-07-31 at 4 29 28 PM" src="https://github.com/user-attachments/assets/97890bba-7b39-4137-b6a5-4b36f38e12b1">

2024-07-31 18:09 UTC, tmolitor-stud-tu commented
1. Product --> Clean Build Folder
2. File --> Packages --> Reset Package Caches
3. Build again

2024-07-31 18:12 UTC, tmolitor-stud-tu commented
Follow https://github.com/monal-im/Monal/wiki/Building-Monal to the letter,
including https://github.com/monal-im/Monal/wiki/Building-Monal#installing-cocoapods