rewrite the Change Password view in SwiftUI
monal-im/Monal pull request #1183
Opened 2024-08-02 02:00 UTC by lissine0

**Notable changes:**
- Disable the "Change Password" button if at least one of the input fields is empty (instead of having a check and an error message)
- Don't prefill the old password for non-Quicksy users (see https://github.com/monal-im/Monal/commit/a426c9a77eaa4f9cd791cf52b2aecbffb37c5b04)
- Changing some of the strings:
    - "Invalid Password" -> "Wrong Password"
So it's clearer that we're talking about the "Current Password" field, not the "New Password" one (e.g. a server may have a restriction on the minimum length.)
Other suggestions: "Incorrect Password"
     - "No accounts connected" -> "Account offline"
This string is displayed when the account we're editing is offline, even if other accounts are online. (the old string is wrong)

**Notes:**
- Changing the password can be so fast that the LoadingOverlay disappears pretty quickly. Should we add a small waiting to make it stay on the screen a bit longer?
- Currently, if we're not connected to the internet, but our account on Monal is enabled, `MLXMPPManager.sharedInstance().getConnectedAccount(forID: accountId)` returns our account instead of returning `nil`, which is presumably a bug
Moreover, the checking of the old password is currently done using the local database: `MLXMPPManager.sharedInstance().isValidPassword(oldPass, forAccount: accountId)`
Combined together, these two things might cause confusion to users in edge-cases. (I can provide an example if you're curious)
 
**Potential improvements:**

- Navigate from the first input field to the second using the keyboard: use .onSubmit and https://developer.apple.com/documentation/swiftui/view/focused(_:equals:)
- Dismiss the "Change Password" view on success (Not sure if this is recommended / a good idea)

Feel free to suggest / make improvements.

2024-08-02 03:11 UTC, tmolitor-stud-tu commented
Just use the relatively new `showPromisingLoadingOverlay()` instead of the old pait of `showLoadingOverlay()` and `hideLoadingOverlay()`.
The promising loading overlay will not only return a promise, but will make that promise wait at least for one second before it gets resolved (it can take longer, if the underlying action (a promise itself) takes longer, though, so that's a minimum bound).

You can see it in action in `MemberList.swift` for example.

> Currently, if we're not connected to the internet, but our account on Monal is enabled, MLXMPPManager.sharedInstance().getConnectedAccount(forID: accountId) returns our account instead of returning nil, which is presumably a bug

No, that's not a bug. The name "connectedAccounts" is merely historic. The right name would be "enabledAccounts" as that's what it is.

You can use the `accountState` property of an xmpp object and check if it is at state `kStateBound` to know if the account is currently connected and logged in etc.

2024-08-02 03:13 UTC, tmolitor-stud-tu commented
That said: even if the account isn't currently connected due to some network outage, the password change IQ will still be sent out on the next connect after doing a smacks resume. If the resume isn't possible, the invalidation handler of the IQ will be called, if there is any.

That can be used to trigger a notification that the password change failed due to network problems and should be retried. That way it won't matter if the account is connected the moment the user tries to change the password.

2024-08-02 03:20 UTC, tmolitor-stud-tu requested changes

2024-08-02 03:20 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +        account.changePassword(newPass) { success, message in
Rewrite `changePassword:` to return a promise so that you can easily use it together with `showPromisingLoadingOverlay`.

2024-08-02 03:20 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                    MLXMPPManager.sharedInstance().updatePassword(newPass, forAccount: accountId)
Rewrite `changePassword:` to use an MLHandler and make that handler fulfill the pending promise (if there is one). That way you will have the promising behaviour usable for the UI while still handling the UI result even if it comes in after the UI was closed or even swiped away (the handler and invalidation handler I already mentioned).

You could show a success or error notification if there is no promise to fulfill (meaning the user closed the UI instead of waiting) and show something in the UI otherwise. I think that would be the most robust solution and provide the best UX :)

2024-08-03 23:37 UTC, tmolitor-stud-tu commented
BTW:

The handler framework is documented over here: https://github.com/monal-im/Monal/wiki/Handler-Framework/

Or in this blog article: https://monal-im.org/post/00007-monal-internals-handlers/

2024-09-15 01:27 UTC, lissine0 commented
(I rebased without introducing any new changes, so you can easily git diff when I do make changes)

2024-09-16 20:34 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +                    MLXMPPManager.sharedInstance().updatePassword(newPass, forAccount: accountId)
This has been a bit hard for me, especially as there are no examples in the codebase of a handler fulfilling a promise. Can I set this aside?

2024-09-17 09:22 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                    MLXMPPManager.sharedInstance().updatePassword(newPass, forAccount: accountId)
The proper solution would be to make promises somehow "serializable". Since promises can't truly survive a process switch/restart, adding all such promises to a global dictionary mapping some random uuid to the promise and use the uuid as serializable argument for MLHandlers, those handlers could simply ask some helper function to provide the corresponding promise, if any, and only fulfill that promise, if one is returned.

--> we need some (small) new framework for this.

Regarding promises per se: `-(AnyPromise*) checkJidType:(NSString*) jid` in `xmpp.m` might give you some inisght on how to return a promise and fulfill it, the usage of that function (in conjunction with the promising loading overlay) can be seen in `AddContactMenu.swift`

2024-09-17 09:39 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +                    MLXMPPManager.sharedInstance().updatePassword(newPass, forAccount: accountId)
> --> we need some (small) new framework for this.

But this is a bit out of scope for this PR, don't you think? 🙂

> Regarding promises in general

The latest version I pushed already uses promises

2024-09-25 00:54 UTC, tmolitor-stud-tu commented
Your code has a flaw: initiating a password change while either being offline or in a slow network condition and then swiping the app away will change the password on the server, but not in monal's password storage.

Use `sendIq:withHandler:` instead of `sendIq:withResponseHandler:andErrorHandler:`

2024-09-25 01:00 UTC, tmolitor-stud-tu commented
...and update the password store in the supplied handler (I'd add the handler to MLIQProcessor.m)

To inform the UI of success/error, we'll need a generalized mapping of uuids to PMKResolver functions. That uuid can be bound to the handler when its created and the handler can later on retrieve the PMKResolver corresponding to that uuid and resolve it, so that the ui is informed properly.

2024-09-25 01:02 UTC, tmolitor-stud-tu commented
That way, `-(AnyPromise*) changePassword:(NSString*) newPass` would still return a promise, but swiping away the app will just kill that promise instead of killing the handling of the iq response...

2024-09-27 01:09 UTC, lissine0 commented
> To inform the UI of success/error, we'll need a generalized mapping of uuids to PMKResolver functions. That uuid can be bound to the handler when its created and the handler can later on retrieve the PMKResolver corresponding to that uuid and resolve it, so that the ui is informed properly.

Another possibility would be using a normal showLoadingOverlay, and posting a notification from the Handler's code, containing any eventual error message.
The ChangePassword view would listen for that notification, and when it arrives, it would hide the LoadingOverlay, and either show success alert or error alert, depending on the metadata in the notification.

2024-09-27 03:04 UTC, tmolitor-stud-tu commented
No, that would mean we'd have to invent new notifications for every signal we want to send to the UI. We need a generalized way to do this and what I suggested is exactly this.

@matthewrfennell could you build that "promise registry" I described in https://github.com/monal-im/Monal/pull/1183#issuecomment-2372653687 (and the following comment)? That would be really nice! Unfortunately my own time is still very limited :(

2024-11-02 21:11 UTC, lissine0 commented
Recent changes:
- Rebase on the develop branch.
- Dismiss the view on success of changing password.
- Don't show the password in cleartext for Quicksy users. But prefill it still.
Instead, it will be shown in cleartext in the Account Settings -> Login Credentials

2024-12-27 07:44 UTC, tmolitor-stud-tu commented
Our new serializable promise framework was now mergend (thanks @matthewrfennell !)

Please adapt this PR to this new framework, you can see an example of such an adaption in 71465822c08b9e7227649e7da5270edda3a83202

2025-01-02 13:58 UTC, matthewrfennell commented on Monal/Classes/ChangePassword.swift
> +    @Environment(\.presentationMode) var presentationMode
[PresentationMode is deprecated now](https://developer.apple.com/documentation/swiftui/presentationmode) - does it work with [DismissAction](https://developer.apple.com/documentation/swiftui/environmentvalues/dismiss)?

2025-01-02 13:58 UTC, matthewrfennell commented on Monal/Classes/xmpp.m
> +    return [promise toAnyPromise];
Promise usage looks good to me!
I tested a password change where the handler gets run by the appex - it got consumed correctly

2025-01-02 15:01 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +    @Environment(\.presentationMode) var presentationMode
Yes, it does
Thanks

2025-01-02 15:07 UTC, tmolitor-stud-tu requested changes

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/xmpp.m
> +    [self sendIq:iqNode withHandler:$newHandlerWithInvalidation(MLIQProcessor, handlePasswordChange,handlePasswordChangeInvalidation, $ID(iqNode), $ID(newPass), $ID(promise))];
binding `iqNode` here on handler creation is a no-op because this var will be shadowed by a call-bound `iqNode` by the iq handling subsystem...the same subsystem binding `account` when calling the handler...

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
old pass should be visible to the user so that it can be copied and used in other non-quicksy clients...

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
this isn't translatable, only Text() or NSLocalizedString() is translatable until someone repairs our translatable string extractor (it normally compiles the code, but that fails, so the NSLocalizedString + Text extraction is some sort of fallback)

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +$$class_handler(handlePasswordChange, $$ID(XMPPIQ*, iqNode), $$ID(xmpp*, account), $$ID(NSString*, newPass), $$ID(MLPromise*, promise))
up to now we never stored the password in the db...with this, the password will be stored in the db at least until the result iq is received (and possibly longer in the binary db data)...

I think a better fix would be to store the password in a temporary keychain using SAMKeychain and a random uuid and only bind the uuid to the handler, then use samkeychain to retrieve the actual password in the handler and write it using MLXMPPManager. Don't forget to remove the temporary password from the temp-keychain in the handler, too.

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +$$class_handler(handlePasswordChangeInvalidation, $$ID(XMPPIQ*, iqNode), $$ID(MLPromise*, promise))
invalidations should be above the corresponding normal handler in code

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
it isn't a timeout but some non-smacks reconnect that can be triggered by a multitude of things. just use a generic `"Could not change password of '%@'!", iqNode.fromUser`

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    DDLogError(@"Changing the password of the account '%@' returned timeout", iqNode.fromUser);
always do the logging first, in case the remaining code has some error crashing the app

2025-01-02 15:07 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +        NSString* errorMessage = [HelperTools extractXMPPError:iqNode withDescription:NSLocalizedString(@"Could not change password", @"")];
this error should name the account in question, too, just like done in the invalidation.

2025-01-02 15:22 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
I disagree about this
If the password is visible, someone who has physical access to your device can steal your password.
The reason why it's shown in clear text in Quicksy, is because Quicksy passwords are auto-generated by default.
Ideally, if a Quicksy user picks a different password, this field wouldn't be prefilled anymore.

2025-01-02 15:42 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
Should these error messages be changed as well?
https://github.com/monal-im/Monal/blob/9865fd0e2/Monal/Classes/MLMucProcessor.m#L1312
https://github.com/monal-im/Monal/blob/9865fd0e2/Monal/Classes/MLMucProcessor.m#L1257
https://github.com/monal-im/Monal/blob/9865fd0e2/Monal/Classes/MLMucProcessor.m#L1057
https://github.com/monal-im/Monal/blob/9865fd0e2/Monal/Classes/MLMucProcessor.m#L602
https://github.com/monal-im/Monal/blob/9865fd0e2/Monal/Classes/MLMucProcessor.m#L527

2025-01-02 15:52 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
hmm, good point :D I guess I used "timeout" instead of no description because it sounds slightly more concrete while still not being completely wrong (the no. one reason for an invalidation is a smacks timeout). At the same time it makes clear that the user can just try again and the error is only ephemeral.

I'm unsure what to do, @matthewrfennell what do you think? Keep the "timeout" or replace all these error messages with a more generic one?

2025-01-02 16:15 UTC, matthewrfennell commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
I think generic is better personally, but making it clear it can be tried again: I can imagine some non-technical users would not even guess that timeout = ephemeral.

Something like this: "Could not do xyz: please try again"?

2025-01-02 17:26 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
Actually it is translatable, here's the initializer being used: https://developer.apple.com/documentation/swiftui/button/init(_:action:)
In fact, here's a button with a slightly different initializer, and a unique string (`Block`), being translated to French:
https://github.com/monal-im/Monal/blob/develop/Monal/Classes/BlockedUsers.swift#L93

<img src="https://github.com/user-attachments/assets/61ae1fde-819d-4a43-98a0-10de76bc5640" width="270" height="480">

2025-01-02 17:56 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
Good idea, sounds perfect :)

2025-01-02 19:23 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
This is about extracting translatable strings into our `Localizable.strings`file, not about strings detected as translated once being in that file.

We are using this set to `NO` because using `YES` tries to compile our code and that somehow fails: https://developer.apple.com/documentation/xcode/build-settings-reference#Localized-String-SwiftUI-Support

Used here: https://github.com/monal-im/Monal/blob/develop/scripts/updateLocalization.sh#L119

I've had multiple instances of `LocalizedStringKey` as argument to some SwiftUI view that weren't translatable in this mode (which is in accordance to the documentation I linked above).

You are right, the button text *is* translatable, but not *extractable*.
You can try the extraction script yourself, if you want to confirm this.

2025-01-02 22:15 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
BlockedUsers.swift was merged on September 29th https://github.com/monal-im/Monal/pull/1236#event-14443115204
And the localization extraction script was last run on October 12th, https://github.com/monal-im/Monal-localization-main/commits/main/Base.lproj/Localizable.strings
The string "Block" only appears in BlockedUsers.swift
Since it's still in Localizable.strings, this means it was extracted, right?

2025-01-02 22:40 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
The [documentation](https://developer.apple.com/documentation/swiftui/button/init(_:action:)#discussion) says that the Button initializer creates a Text view on your behalf.
If the localization extraction script works on Buttons, that's probably why.

2025-01-02 22:42 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
I agree that it's a good idea for the user-facing errors.
But for logs, wouldn't it be better to explain why the operation failed? (non-smacks reconnect)

2025-01-02 22:43 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +$$class_handler(handlePasswordChange, $$ID(XMPPIQ*, iqNode), $$ID(xmpp*, account), $$ID(NSString*, newPass), $$ID(MLPromise*, promise))
The latest version I force-pushed implemented this

2025-01-03 09:07 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
okay, sounds reasonable.
So we should only show the password as long as it is the autogenerated one.

2025-01-03 09:16 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    NSString* errorMessage = [NSString stringWithFormat:NSLocalizedString(@"Changing the password of the account '%@' returned timeout", @""), iqNode.fromUser];
the logging already includes the function that logs this (the invalidation handler). that means the information is already there and I don't care that much, if the logged text contains "timeout", "some error" or any other description (as long as the description still contains the fact that there was an error setting the password).

2025-01-03 09:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
I now spend >1 hour testing your hypothesis (my local dev environment differed from the build server so that the extraction didn't work at all) and the result is: button texts aren't extracted by our extraction script when `SWIFT_EMIT_LOC_STRINGS = NO`. Just like the documentation says. The reason is: swift code isn't compiled in that case. And without compiling, only a simple regex matcher extracting strings from `Text()` is used.

Example code for you to test it yourself:
```
Button("lksfjkfjlkfa", role:.destructive) {
    print("doing nothing...")
}
Text("lksfjkfjlkfa: XXX")
```

`lksfjkfjlkfa: XXX` gets added to our base `Localizable.strings`, but `lksfjkfjlkfa` isn't. Just like I said.

Why is `Block` still in there? I guess the auto-removal of strings not used anymore doesn't work correctly (I always tried to be conservative here, because we don't want to delete needed strings already translated. Undoing their work would make translators really unhappy.).

The "Block" string was already present in the objc code (that got extracted correctly) and was never removed, so the button still gets correctly translated now, even though the string isn't extractable and removing "Block" from the `Localizable.strings` file and running the extraction script wouldn't add it back in.

That should be fixed, of course (e.g. using the button `label` argument with a `Text()`).

The better fix would be to make the extraction work with `SWIFT_EMIT_LOC_STRINGS = YES`. All quirks would go away in this case and every invocation of a function taking a `LocalizedStringKey` would automatically be correctly extracted, even our own functions :)
@matthewrfennell if you want to experiment a bit, you can try to fix that. Last time I tried, I couldn't get it to work and eventually gave up, but maybe you'll have more luck :)

2025-01-03 09:56 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +$$class_handler(handlePasswordChange, $$ID(XMPPIQ*, iqNode), $$ID(xmpp*, account), $$ID(NSString*, newPass), $$ID(MLPromise*, promise))
You implementation has a few small quirks that should be addressed (order of SAMKeychain calls, usage of uuid and jid for the keychain etc.). I'll do this myself once merged to not delay this PR further.

2025-01-03 10:59 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +            actions: { Button("Close", action: alertPrompt.dismissCallback ?? {}) },
Correction: deleting unused string works as intended: "Block" doesn't exist after running our extractions script.

We are only extracting strings from beta builds to make the strings more stable. Your new blocking interface isn't yet in beta/stable but only in alpha builds.
--> "Block" is still present in the current `Localizable.strings` files.

2025-01-03 11:26 UTC, tmolitor-stud-tu requested changes

2025-01-03 11:26 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
I know of many users that are actively using and needing this functionality, I can't merge this without showing at least the autogenerated password.

2025-01-03 11:26 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                SecureField("New Password", text: $newPass)
Same as for Buttons, not translatable without NSLocalizedString (see PasswordMigration.swift for an example).

2025-01-03 15:02 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
If they are Quicksy users, the old password will be pre-filled, but not shown in cleartext.
They can change it without knowing the old password.

2025-01-03 16:36 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
I know, but to set up the same account on other apps, they need a way to get the password in cleartext.

Please make the password visible in cleartext if it is the autogenerated one.

2025-01-03 17:46 UTC, lissine0 commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
I'm now prefilling it and showing it in clear text for all Quicksy users.
But ideally, this should be changed in the future so it happens only with auto-generated passwords.

2025-01-03 17:58 UTC, tmolitor-stud-tu commented on Monal/Classes/ChangePassword.swift
> +                SecureField("Current Password", text: $oldPass)
> But ideally, this should be changed in the future so it happens only with auto-generated passwords.

yes, that would be perfect. I'd use defaultsdb setting for this, since quicksy can only have one account. don't forget to set/reset it on account creation.

2025-01-04 12:55 UTC, tmolitor-stud-tu approved these changes

2025-01-04 12:59 UTC, tmolitor-stud-tu commented
lissine: could you squash the first 4 commits (the commits implementing the change password stuff)?

2025-01-04 13:03 UTC, lissine0 commented
> lissine: could you squash the first 4 commits (the commits implementing the change password stuff)?

Done

2025-01-04 13:15 UTC, merged