Adding MediaGallery
monal-im/Monal pull request #1187
Opened 2024-08-02 23:39 UTC by thevaidik

As described adding media gallery, where users can see sent and received media in a chat.

2024-08-15 15:31 UTC, tmolitor-stud-tu requested changes

2024-08-15 15:31 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +//////////////
why add even more `//`?

2024-08-15 15:31 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +                                        try! NSData(contentsOfFile:info["cacheFile"] as! String) as Data
that won't work properly for videos, because NSData is an in-memory structure and videos are usually really big

2024-08-15 15:31 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +            "AVURLAssetOutOfBandMIMETypeKey": mimeType
That's an apple-private symbol not allowed to be used in apps uploaded to the appstore!

2024-08-20 21:41 UTC, tmolitor-stud-tu requested changes

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactDetails.swift
> +                    NavigationLink(destination: MediaGalleryView(contact: contact.contactJid as String, accountNo: NSNumber(integerLiteral: contact.accountId))) {
You want to load this lazy to not load every media file if the user only opens the contact details, example:

```
NavigationLink(destination: LazyClosureView(OmemoKeysView(omemoKeys: OmemoKeysForChat(viewContact: contact)))) {
    Text("Encryption Keys")
}
```

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +                    NavigationLink(destination: MediaItemSwipeView(currentItem: item, allItems: mediaItems)) {
Load this lazy, too

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    func getValue<T>(_ key: String, as type: T.Type) -> T? {
why that? you can just use `as! String` or `as? String` instead of this `getValue()`

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    func getFilePath() -> String? {
This doesn't seem to be used anywhere. Please don't add dead code.

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    func getMimeType() -> String? {
This doesn't seem to be used anywhere. Please don't add dead code.

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    func getFileName() -> String? {
This doesn't seem to be used anywhere. Please don't add dead code.

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +                Image(systemName: "exclamationmark.triangle")
Show a loading indicator while this is `nil`, `generateThumbnail` will already take care that a proper icon is used if loading fails (exclamationmark.triangle or a photo/video/doc icon)

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +            ForEach(allItems.indices, id: \.self) { index in
This won't be lazy. Please try your implementation using 4000 photos and videos to check if it is performant enough.

Just use a loop to fill the gallery with the same photo and video in an alternating fashion to test this.

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    private func loadMediaItems() {
This won't be lazy, generate the thumbnail (meaning: create the `MediaItem` instance only when the view displaying it is initialized (e.g. move the creation of `MediaItem` into the constructor of `MediaItemView`

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    let allItems: [MediaItem]
Use the filetransfer info instead of a fully initialized `MediaItem` and only initialize a `MediaItem` once it is needed (e.g. displayed by swiping left/right)

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +                ForEach(mediaItems) { item in
See my comment (about looping over the info dictionary) below.

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    @Environment(\.presentationMode) var presentationMode
This isn't used anywhere!

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +extension UIImage {
This should be part of `SwiftHelpers.swift` or, even better, `HelperTools.m` or, the best option, be a new objc category `UIImage+Thumbnail.h` + `UIImage+Thumbnail.m`

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +                                        try! NSData(contentsOfFile:info["cacheFile"] as! String) as Data
I wrote you an explanation in chat, but here it is again for completeness:

This will try to share a jpeg image instead of the video, but that apparent jpeg image will have the contents of the video.

Furthermore the video data will be completely loaded into memory (`NSData`) before sharing it. Videos can get quite big (several hundrets or even thousands of megabytes), loading them all into memory is a bad idea.

`ShareLink` has a constructor allowing you to use a file url instead of `NSData`

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +            "AVURLAssetOutOfBandMIMETypeKey": mimeType
Please refactor the code to use my code creating an `AVURLAsset` using the symlink method on ios 16 and the proper public symbol (`AVURLAssetOverrideMIMETypeKey`) on ios 17.

2024-08-20 21:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +            "AVURLAssetOutOfBandMIMETypeKey": mimeType
Please refactor the code of `MLFileTransferVideoCell.m` to use that `AVURLAsset` creating utility function, too. This utility function should be part of the  `SwiftHelpers` class in `SwiftHelpers.swift` and be bridged from `HelperTools.m` like done with the `_renderUIImageFromSVG` method already in `SwiftHelpers.swift`.

2024-08-20 21:47 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactDetails.swift
> +                    NavigationLink(destination: MediaGalleryView(contact: contact.contactJid as String, accountNo: NSNumber(integerLiteral: contact.accountId))) {
This is the wrong place to add a media gallery navigation link, this should be somewhere below encryption keys (beneath the already existing files link)

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/ContactDetails.swift
> +                    }                }
Minor: the formatting looks a bit strange

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaGallery.swift
> +                   !((fileInfo["needsDownloading"] as? NSNumber)?.boolValue ?? true) &&
I feel extracting this expression into several conditions would make it easier to understand in one go. E.g something like:

```swift
fileIsDownloaded(fileInfo) && isDisplayableMediaType(mimeType)
```

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaGallery.swift
> +                if let hostingController = UIApplication.shared.windows.first?.rootViewController?.presentedViewController as? UIHostingController<AnyView> {
My XCode is complaining saying windows was deprecated in iOS 15.0.
I haven't tried it - but could something [like this](https://stackoverflow.com/a/68989580) work?

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaGallery.swift
> +    func generateThumbnail() async {
If I have a wide image (or video) the thumbnail gets squished. For instance - this wide image looks like this:

![wide-image-full](https://github.com/user-attachments/assets/981513ed-484a-4b27-90ec-f0ca4b397b10)

But then gets horizontally squished in the thumbnail:

![wide-image-preview](https://github.com/user-attachments/assets/cfc67418-d830-47af-9a5c-a1f9a19d43de)

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaGallery.swift
> +struct ImageViewerWrapper: View {
If I close an image, I feel it should take me back to the media gallery. Instead, it takes me back to the chat itself:

https://github.com/user-attachments/assets/04a3095d-1fc9-4498-a146-23df393f047d

Maybe even with the system back button?

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaGallery.swift
> +            await generateThumbnail()
My XCode is giving a warning saying (here and on line 78 below):

"Passing argument of non-sendable type 'MediaItem' into main actor-isolated context may introduce data races"

To be honest, I don't fully understand it :) but [this guide](https://code.kiwi.com/articles/swift-5-10-concurrency-survival-guide/) seems like it might help.

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaViewer.swift
> +struct SVGRepresentation: Transferable {
Is there any way to combine / deduplicate these three classes? It feels like they're doing _almost_ exactly the same thing.

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaGallery.swift
> +struct ImageViewerWrapper: View {
The close button works on iPhone, but doesn't seem to work on iPad:


https://github.com/user-attachments/assets/67aec727-7a0f-4c8d-8e06-f04f94cde48a

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaViewer.swift
> +    init(delegate: SheetDismisserProtocol, info:[String:AnyObject]) throws {
Minor: spaces after the colons should be consistent

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaViewer.swift
> +            controlsVisible = !controlsVisible
Will do the same thing, but I think `.toggle()` is more idiomatic

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaViewer.swift
> +        print("Created AVPlayer(\(mimeType)): \(String(describing: player))")
We should use `DDLogDebug` or similar here

2024-08-20 22:55 UTC, matthewrfennell commented on Monal/Classes/MediaViewer.swift
> +        } else if (info["mimeType"] as! String).hasPrefix("video/") {
I'm not sure if I have any solutions :) but it feels like we are always having to check between these three mime types in multiple places in the code. Is there any way we can put all of the logic for each one in their own class, or extract these checks out some other way?

Ideally, if we want to add support for a new mime type, we would have to do it in one place only. It may not be possible to reach that ideal, but thought I'd comment in case you have any ideas :)

2024-08-20 23:06 UTC, lissine0 commented on Monal/Classes/MediaGallery.swift
> +//  Copyright © 2021 Monal.im. All rights reserved.
Please set the correct year here. It's useful to easily know roughly when a source file was created.

2024-08-20 23:06 UTC, lissine0 commented on Monal/Classes/MediaGallery.swift
> +// MediaGallery.swift
Please add a space to have the same indentation

2024-08-20 23:08 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +//
Please remove the first set of vertical //

2024-08-20 23:10 UTC, lissine0 commented on Monal/Classes/MediaGallery.swift
> +//  Created by Vaidik(vaidik50000@gmail.com).
You can remove the email address, and add the creation date (you can set it to today), so it's consistent with the rest of the codebase.
Your email address is in the git commit metadata. It's visible in git log.

2024-08-21 00:01 UTC, lissine0 commented on Monal/Classes/ContactDetails.swift
> +                    NavigationLink(destination: MediaGalleryView(contact: contact.contactJid as String, accountNo: NSNumber(integerLiteral: contact.accountId))) {
contact.accountId is already an NSNumber https://github.com/monal-im/Monal/blob/develop/Monal/Classes/MLContact.h#L51
No need to cast it (implicitly) to integer and immediately back to NSNumber.
You can pass it directly.

2024-08-21 10:16 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +    private var invalidFileView: some View {
For better performance, make this a struct that conforms to View.
For more details, see [this](https://medium.com/@vladislavshkodich/mastering-swiftui-are-you-really-as-good-as-you-think-40a4953f7e88#4127)

2024-08-21 10:17 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +    private var controlsOverlay: some View {
Same here. Make this a struct that conforms to View

2024-08-21 10:31 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +    private var controlsOverlay: some View {
When you change it to struct, you should also make it conform to Equatable, as that'll achieve better performance.
For more details, see [this](https://medium.com/@vladislavshkodich/mastering-swiftui-are-you-really-as-good-as-you-think-40a4953f7e88#1adf)

2024-08-21 10:51 UTC, lissine0 commented on Monal/Classes/MediaGallery.swift
> +    func generateThumbnail() async {
This is due to .scaledToFill in L177
See if it looks better with .scaledToFit instead

2024-08-21 10:52 UTC, lissine0 commented on Monal/Classes/MediaGallery.swift
> +                    .resizable()
.resizable() is applied in both cases. So, it should be applied on the whole Group instead.

2024-08-21 11:03 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +                    VStack {
This VStack isn't needed because it only contains one subview.

2024-08-21 11:09 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +            if (info["mimeType"] as! String).hasPrefix("image/svg") {
The case of svg images should be inside the L73,85 code block, like the case of gif images.
(also, .scaledToFit() is missing )

2024-08-21 11:15 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +                if let image = UIImage(contentsOfFile:info["cacheFile"] as! String) {
The image constant is only used in the else statement (L81)
If it's not needed in the case of gifs and SVGs, then the declaration should be moved down to L80
@tmolitor-stud-tu thoughts?

2024-08-21 11:38 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +                                        try! NSData(contentsOfFile:info["cacheFile"] as! String) as Data
The argument to SVGRepresentation, GifRepresentation,(L148) JpegRepresentation (L156) is the same.
It can be made a constant that's computed once beforehand, and passed to the structs.

2024-08-21 11:56 UTC, tmolitor-stud-tu commented
Thats code originally written by me. If I recall correctly there was a reason to not integrate svg images more. I think it was because the svgview is NOT an image and as such doesn't allow us to use the same view modifiers as the Image view...

Am 21. August 2024 13:10:05 MESZ schrieb lissine0 ***@***.***>:
>@lissine0 commented on this pull request.
>
>
>
>> +    @State private var previewImage: UIImage?
>+    @State private var controlsVisible = false
>+    @StateObject private var customPlayer = CustomAVPlayer()
>+    @State private var isPlayerReady = false
>+
>+    init(delegate: SheetDismisserProtocol, info:[String:AnyObject]) throws {
>+        self.delegate = delegate
>+        self.info = info
>+    }
>+    
>+    var body: some View {
>+        ZStack(alignment: .top) {
>+            Color.background
>+                .edgesIgnoringSafeArea(.all)
>+            
>+            if (info["mimeType"] as! String).hasPrefix("image/svg") {
>
>The case of svg images should be inside the L73,85 code block, like the case of gif images.
>(also, .scaledToFit() is missing )
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/1187#pullrequestreview-2250499938
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

2024-08-21 12:07 UTC, tmolitor-stud-tu commented
I *think* there was a layout/spacing issue (for gifs of certain sizes/aspect ratios?) without that VStack, so I added this extra VStack to fix that...but maybe that was something superseded later on in the development cycle of my original image viewer and isn't needed anymore?

Am 21. August 2024 13:03:46 MESZ schrieb lissine0 ***@***.***>:
>@lissine0 commented on this pull request.
>
>
>
>> +    }
>+    
>+    var body: some View {
>+        ZStack(alignment: .top) {
>+            Color.background
>+                .edgesIgnoringSafeArea(.all)
>+            
>+            if (info["mimeType"] as! String).hasPrefix("image/svg") {
>+                VStack {
>+                    ZoomableContainer(maxScale:8.0, doubleTapScale:4.0) {
>+                        SVGView(contentsOf: URL(fileURLWithPath:info["cacheFile"] as! String))
>+                    }
>+                }
>+            } else if (info["mimeType"] as! String).hasPrefix("image/") {
>+                if let image = UIImage(contentsOfFile:info["cacheFile"] as! String) {
>+                    VStack {
>
>This VStack isn't needed because it only contains one subview.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/1187#pullrequestreview-2250488002
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

2024-08-21 12:08 UTC, tmolitor-stud-tu commented
No, that won't work, svg images are rendered entirely different and aren't image views at all...

Am 21. August 2024 13:10:05 MESZ schrieb lissine0 ***@***.***>:
>@lissine0 commented on this pull request.
>
>
>
>> +    @State private var previewImage: UIImage?
>+    @State private var controlsVisible = false
>+    @StateObject private var customPlayer = CustomAVPlayer()
>+    @State private var isPlayerReady = false
>+
>+    init(delegate: SheetDismisserProtocol, info:[String:AnyObject]) throws {
>+        self.delegate = delegate
>+        self.info = info
>+    }
>+    
>+    var body: some View {
>+        ZStack(alignment: .top) {
>+            Color.background
>+                .edgesIgnoringSafeArea(.all)
>+            
>+            if (info["mimeType"] as! String).hasPrefix("image/svg") {
>
>The case of svg images should be inside the L73,85 code block, like the case of gif images.
>(also, .scaledToFit() is missing )
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/1187#pullrequestreview-2250499938
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

2024-08-21 12:09 UTC, tmolitor-stud-tu commented
Yeah, good catch. I was a but lazy when writing the original image viewer...

Am 21. August 2024 13:38:23 MESZ schrieb lissine0 ***@***.***>:
>@lissine0 commented on this pull request.
>
>
>
>> +    
>+    private var controlsOverlay: some View {
>+        VStack {
>+            Color.background
>+                .edgesIgnoringSafeArea(.all)
>+                .overlay(
>+                    HStack {
>+                        Spacer().frame(width:20)
>+                        Text(info["filename"] as! String).foregroundColor(.primary)
>+                        Spacer()
>+                        
>+                        if let image = previewImage {
>+                            if (info["mimeType"] as! String).hasPrefix("image/svg") {
>+                                ShareLink(
>+                                    item: SVGRepresentation(getData: {
>+                                        try! NSData(contentsOfFile:info["cacheFile"] as! String) as Data
>
>The argument to SVGRepresentation, GifRepresentation,(L148) JpegRepresentation (L156) is the same.
>It can be made a constant that's computed once beforehand, and passed to the structs.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/1187#pullrequestreview-2250556777
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

2024-08-21 12:28 UTC, lissine0 commented on Monal/Classes/MediaViewer.swift
> +                                )
The only difference between the three Sharelinks, is the argument passed to `item:` (L
And that argument always [depends on the same value](https://github.com/monal-im/Monal/pull/1187/commits/0f9faea#r1724902386).
Thus, only one ShareLink should be used, and the correct *Representation struct should be passed to it.

2024-08-21 12:54 UTC, lissine0 commented
@tmolitor-stud-tu the question is if MediaViewer [L74](https://github.com/thevaidik/Monal-dev/blob/0f9faea/Monal/Classes/MediaViewer.swift#L74) is needed or not when the image is a gif.
If it is not needed for gifs, then that `if let image = ...` can be moved to [L80](https://github.com/thevaidik/Monal-dev/blob/0f9faea/Monal/Classes/MediaViewer.swift#L80).
In that case, the the test for image/svg prefix can be moved down next to the test for image/gif, and it won't be a problem as the GIFViewer and SVGView are separate views, and only one would be visible at a time.
Moreover, the modifiers are already directly applied to the `GIFViewer` and `Image`, and thus image modifiers won't be an issue

2024-08-21 13:15 UTC, lissine0 commented
> I *think* there was a layout/spacing issue (for gifs of certain sizes/aspect ratios?) without that VStack, so I added this extra VStack to fix that...but maybe that was something superseded later on in the development cycle of my original image viewer and isn't needed anymore?

Maybe you're thinking about [this](https://github.com/thevaidik/Monal-dev/blob/0f9faea/Monal/Classes/MediaViewer.swift#L127) VStack instead?
It has only one subview, but it has [`.frame(height: 80)`](https://github.com/thevaidik/Monal-dev/blob/0f9faea/Monal/Classes/MediaViewer.swift#L175) applied to it.

2024-08-24 17:38 UTC, tmolitor-stud-tu requested changes
still things to solve, in particular cleaning up the code and solving the performance issues (lazy loading!).

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactDetails.swift
> +
why that extra empty line?

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactDetails.swift
> +                    NavigationLink(destination: LazyClosureView{MediaGalleryView(contact: contact.contactJid as String, accountNo: NSNumber(integerLiteral: contact.accountId))}) {
`contact.accountId` already is a `NSNumber` no need to convert it

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +//  Created by Vaidik on 21.09.24.
why is that date in the future? shouldn't it e roughly around the date you first created this pull request (~3 weeks ago)?

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +            await generateThumbnail()
Lets ignore that warning for now :)

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +                    .scaledToFill()
Your if statement is not clean and the else case is never reached at all, consider cleaning this up:
```suggestion
            if if let thumbnail = item.thumbnail {
                Image(uiImage: thumbnail)
                    .resizable()
                    .scaledToFill()
            } else {
                ProgressView()
                    .progressViewStyle(CircularProgressViewStyle())
                    .frame(width: 50, height: 50)
            }
```

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +            } else {
this else will *never* be reached.

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +                    .resizable()
That's resolved, the else is never hit now :D

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    let allItems: [MediaItem]
What about this?

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +struct ImageViewerWrapper: View {
I think this is because of line 212: https://github.com/monal-im/Monal/pull/1187/files#diff-3d6e9cc2651763650c1a8ebdb0c7e9c0c6afa12a96d5d995df6a4ce5fd364568R212

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +struct ImageViewerWrapper: View {
Also Line 212, I guess

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +                if let image = UIImage(contentsOfFile:info["cacheFile"] as! String) {
the `if let image` is used to detect if this is a regular image and show the "invalid image" ui if it is not. even though it will not be used in the gif case (we won't show the static image, but an animated version in this case).

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +                                        try! NSData(contentsOfFile:info["cacheFile"] as! String) as Data
loading all the date even though the user ma never press the share button would cost a lot of memory.

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +                                )
you will only be able to create the correct representation struct once you checked the mime type. creating a let constant containing the representation struct will make you replicate the mime-type if statements. I tested both and found the replicated sharelink code slightly more readable than the replicated if statements.

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +        } else if (info["mimeType"] as! String).hasPrefix("video/") {
hmm, that would be really cool. I don't have a concrete idea on how to accomplish this, though. if you have a concrete code suggestion, let me know :)

2024-08-24 17:38 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +            "AVURLAssetOutOfBandMIMETypeKey": mimeType
this one isn't solved yet

2024-08-24 17:44 UTC, tmolitor-stud-tu commented
Why didn't you add a preview image to the share link in case of a video? We even have a thumbnail generating function for videos now, why not use that?

2024-08-24 17:52 UTC, thevaidik commented on Monal/Classes/MediaGallery.swift
> +//  Created by Vaidik on 21.09.24.
I'll fix it, someone said to make it on the day of final pr in comments, so I did it.

2024-08-24 20:41 UTC, tmolitor-stud-tu requested changes

2024-08-24 20:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +//  Created by Vaidik on 01.09.24.
still in the future, right? :D

2024-08-24 20:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    private func loadMediaItems() {
wrong name of this function

2024-08-24 20:41 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    func generateThumbnail() async {
Is that fixed now?

2024-08-24 23:47 UTC, thevaidik commented on Monal/Classes/MediaGallery.swift
> +    private func loadMediaItems() {
what about "retrieveAvailableMediaItems()" ?

2024-08-24 23:48 UTC, thevaidik commented on Monal/Classes/MediaGallery.swift
> +    private func loadMediaItems() {
or "fetchDownloadedMediaItems()"

2024-08-25 13:15 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    private func loadMediaItems() {
`fetchDownloadedMediaItems` sounds good... `getDownloadedMediaItems` woul be another joice

2024-08-25 13:34 UTC, tmolitor-stud-tu requested changes

2024-08-25 13:34 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +                   !((fileInfo["needsDownloading"] as? NSNumber)?.boolValue ?? true) &&
you are right...but now the if statement is multiline which is okay imho :)

2024-08-25 13:34 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +                    VStack {
Lets keep that and, if you want, you can test it after we merged this PR :)

2024-08-25 13:34 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +        } else if (info["mimeType"] as! String).hasPrefix("video/") {
Let's merge this PR and figure that out afterwards :)

2024-08-29 00:36 UTC, tmolitor-stud-tu requested changes

2024-08-29 00:36 UTC, tmolitor-stud-tu commented on Monal/Classes/HelperTools.m
> +        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
this is complete bullshit and creates all sorts of race conditions!

let the user provide a callback taking the AVURLAsset as argument and remove the symlink after that callback returns

2024-08-29 00:36 UTC, tmolitor-stud-tu commented on Monal/Classes/HelperTools.m
> ++ (nullable AVURLAsset *)createAVURLAssetWithFilePath:(NSString *)filePath
wrong coding style!
https://github.com/monal-im/Monal/wiki/Code-style

and: _Nullable instead of nullable

and: don't use NSLog but proper DDLogXXX

2024-08-29 00:36 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaGallery.swift
> +    func generateThumbnail() async {
@matthewrfennell I guess we'll have to fix this ourselves after merging the PR

2024-08-29 00:36 UTC, tmolitor-stud-tu commented on Monal/Classes/MediaViewer.swift
> +//class CustomAVPlayer: ObservableObject {
why this huge commented out code block??

2024-08-29 00:36 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftHelpers.swift
> +extension UIImage {
@matthewrfennell @lissine we will have to fix that (write a HelperTools function instead of this swift extension so that it can be used everywhere in monal, not just by 
swift code

or, even better: use the already existing HelperTools function `+(void) addUploadItemPreviewForItem:(NSURL* _Nullable) url provider:(NSItemProvider* _Nullable) provider andPayload:(NSMutableDictionary*) payload withCompletionHandler:(void(^)(NSMutableDictionary* _Nullable)) completion` for generating thumbnails (maybe extend it to properly generate thumbnails for videos if not already supported)

2024-08-29 03:28 UTC, tmolitor-stud-tu commented
Cherry-picked and closed now, see here for a tracker of open issues: https://github.com/monal-im/Monal/pull/1221

2024-08-29 03:28 UTC, closed without merging