Preparation for OmemoKeys ViewController
monal-im/Monal pull request #1189
Opened 2024-08-03 14:08 UTC by matthewrfennell

These are all purely refactors, there should be no change in behaviour.
Main purpose is to simplify `OmemoKeys` where there is logic that can be pushed out of the view, or removing state where we can use functions instead.

2024-08-03 23:34 UTC, tmolitor-stud-tu requested changes
Please change `MLContact` so that it has an `account` property that does what `getAccountBelongingToContact` does. This is cleaner than an aux function in Swift. And it has the nice side effect that it can also be used from objc.

Please update `MLCall` to use this new property of `MLContact` in its `-(xmpp*) account` method.

BTW: `getAccountBelongingToContact` should have been in `SwiftHelpers.swift` instead of `SwiftuiHelpers.swift`.

2024-08-06 04:24 UTC, tmolitor-stud-tu approved these changes
I marked a minor nitpick. I saw you using `.obj` only in `.init` methods, so that's probably fine, but for clarity and to counter copy-paste bugs later on, this should be changed.

I'll merge it nonetheless, you can open a new PR for that minor thing :)

2024-08-06 04:24 UTC, tmolitor-stud-tu commented on Monal/Classes/MemberList.swift
> +        account = mucContact.obj.account! as xmpp
You only have to use `.obj` if you are accessing a method of an `ObservableKVOWrapper` wrapped objc object, accessing a property of such an object (without n`.obj`) works just fine. And it has the additional benefit of emitting SwiftUI `ObservableObject` signals on KVO changes of that property in objc land.

2024-08-06 04:24 UTC, merged

2024-08-06 07:56 UTC, matthewrfennell commented on Monal/Classes/MemberList.swift
> +        account = mucContact.obj.account! as xmpp
Is there something special I have to do to allow it? When I try this I get "Generic parameter 'T' could not be inferred".

<img width="1017" alt="screenshot-1" src="https://github.com/user-attachments/assets/9604b0dc-0553-4340-85b5-64003ce6a9d7">

2024-08-06 08:47 UTC, tmolitor-stud-tu commented
You have to cast it for Swift's type system to be able to infer the type of the generic parameter...
An 'as! xmpp' should suffice :)

Am 6. August 2024 09:56:39 MESZ schrieb Matthew Fennell ***@***.***>:
>@matthewrfennell commented on this pull request.
>
>
>
>> @@ -30,7 +30,7 @@ struct MemberList: View {
>     @StateObject private var overlay = LoadingOverlayState()
> 
>     init(mucContact: ObservableKVOWrapper<MLContact>) {
>-        account = MLXMPPManager.sharedInstance().getConnectedAccount(forID: mucContact.accountId)! as xmpp
>+        account = mucContact.obj.account! as xmpp
>
>Is there something special I have to do to allow it? When I try this I get "Generic parameter 'T' could not be inferred".
>
><img width="1017" alt="screenshot-1" src="https://github.com/user-attachments/assets/9604b0dc-0553-4340-85b5-64003ce6a9d7">
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/1189#discussion_r1705082487
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>