SwiftUI contact list
monal-im/Monal pull request #1205
Opened 2024-08-12 18:33 UTC by matthewrfennell

# Introcution

This PR implements the first part of #1094

To do in (if it's ok) future PRs:

- Use `ObservableKVOWrapper<MLContact>` everywhere for live updates
- Implement notification badge for `ContactEntry` to match the old contacts screen
- Delete unused code from `ContactsViewController.m` etc.
- #121

# Videos

## iPhone

https://github.com/user-attachments/assets/60c4f99f-fb5d-4bab-ba37-6a3662573d6e

## iPad

At 2:22, the contact gets deleted from another device.

https://github.com/user-attachments/assets/990247f4-475e-41a4-99ad-f22e6f260401

## Animated notification badge

Just before raising this PR, I noticed the contact request notification badge wasn't animated.
I didn't want to re-record everything, so here's a recording of just that animation.

https://github.com/user-attachments/assets/5bafecbe-fab8-4e68-87a1-d9216fce8ea8

2024-08-15 13:46 UTC, tmolitor-stud-tu requested changes

2024-08-15 13:46 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactsView.swift
> +            // We do not use a Button with destructive role here as we would like to display the confirmation dialog first.
That's very nice! could you add that behaviour to the group members list, too?

2024-08-15 13:46 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactsView.swift
> +            NavigationStack {
Would be nicer to not open a new navigation stack here, but use the current one (that would look nice even on ipad/macos, I guess) and let the user return to the contact list by using the back button.

2024-08-18 22:00 UTC, matthewrfennell commented
Here's how it looks now:

https://github.com/user-attachments/assets/d2aa2eff-910a-41ba-8767-ef528ab720a5

There is one edge case: if the view size changes from regular to compact (or vice versa) while the view is open, the button doesn't get added or removed:

https://github.com/user-attachments/assets/dee7262e-f553-42d2-9b7c-7aac94b39d6c

I'm looking into this now, but it might take some time to work out. It may be easier to wait until the ActiveChatsViewController is also SwiftUI.

2024-08-20 20:12 UTC, tmolitor-stud-tu commented
Regarding the back button stuff: have a look at `MLSplitViewDelegate.m`.

This should allow you to trigger an event if the split view type (compact/expanded) changes and react accordingly in swiftui.

It will allow you to remove the code passing in the state (`horizontalSizeClass`, `shouldDisplayBackButton` etc.) all the way from active chats down to the swiftui view, too :)

2024-08-24 18:02 UTC, matthewrfennell commented
GitHub is getting stuck uploading the video. So here's a blurry gif instead :)

https://github.com/user-attachments/assets/9af4f125-b06f-4377-a179-231c8479e18b

2024-08-24 18:03 UTC, tmolitor-stud-tu commented
I feel like `shouldAlwaysDisplayBackButton`isn't needed anymore, right?

Is the `SizeClassWrapper` needed? Wouldn't it be better to just add that `horizontal` property to `ActiveChats` directly (renamed to `horizontalSizeClass`, of course)

2024-08-24 21:30 UTC, matthewrfennell commented
Here's how the `ContactDetails` view dismiss button looks now:

https://github.com/user-attachments/assets/6c53de4a-93bd-4b17-b6bd-4e048652fc53

2024-08-29 00:17 UTC, merged

2024-08-29 00:18 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactsView.swift
> +            // We do not use a Button with destructive role here as we would like to display the confirmation dialog first.
Don't forget this one :)