[Draft]: Streamline code
monal-im/Monal pull request #1208
Opened 2024-08-17 03:30 UTC by lissine0

Note: did not check the instances where accountNo / accountId is NSString.
And the PR is not ready yet, it needs more reviewing and testing.
Fixes https://github.com/monal-im/Monal/issues/1188

2024-08-20 20:00 UTC, tmolitor-stud-tu requested changes
Didn't we settle with `accountId` instead of `accountID`? I'm a bit unsure because we switched that back and forth while discussing. It could well be that I'm mistaken, of course.

There are other constants (muc affiliations and muc roles) currently hardcoded as strings throughout the code. These ones should be mase string constants, too (sorry I did not mention this earlier, I just catched that one while reviewing your pr).

2024-08-20 20:00 UTC, tmolitor-stud-tu commented on Monal/Classes/MLConstants.h
> +#define mucTypeGroup @"group"
Define this in the block starting at line ~143

2024-08-20 20:00 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactDetails.swift
> +                    if contact.isMuc && ((contact.groupSubject as String).count > 0 || ownRole == "moderator") {
Roles should be made string constants, too. At least those we are using in the code. Same with affiliations ('owner', 'admin', 'member' etc.).

2024-08-20 20:00 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftHelpers.swift
> +let mucTypeGroup = HelperTools.getObjcDefinedValue(.mucTypeGroup)
Should also have a `k` prefix here.

2024-08-20 20:00 UTC, tmolitor-stud-tu commented on Monal/Classes/HelperTools.m
> +        case MLDefinedIdentifier_mucTypeGroup: return mucTypeGroup; break;
`k` prefix ;)

2024-08-20 21:54 UTC, lissine0 commented
> Didn't we settle with `accountId` instead of `accountID`? I'm a bit unsure because we switched that back and forth while discussing. It could well be that I'm mistaken, of course.

We did when we found out that `accountId` is used more in the codebase than `accountID`
But I was curious what Apple uses. And I learned that in their frameworks (Foundation, SwiftUI), >90% of the time they use Identifier. But when they don't, they use ID.
Examples: [1](https://developer.apple.com/documentation/foundation/nsdictionary/1412281-fileowneraccountid) [2](https://developer.apple.com/documentation/swiftui/scrollposition/viewid) [3](https://developer.apple.com/documentation/swiftui/tabviewcustomization/subscript(sectionid:)) [4](https://developer.apple.com/documentation/foundation/nsxmlparser/1411917-systemid?language=objc) [5](https://developer.apple.com/documentation/foundation/nsxmlparser/1411917-systemid?language=objc)

However, I also discovered that in some of their WWDC swift code examples, they used [bookId](https://developer.apple.com/videos/play/wwdc2022/10061/) and [recipeId](https://developer.apple.com/videos/play/wwdc2022/10054/), and in some they used [uniqueID](https://developer.apple.com/videos/play/wwdc2024/10185/).
But bookId was a local closure parameter, and recipeID was the argument to the defintion of a subscript.
I guess they used fooId for local variables, and barID for anything viewable from outside the class.
But I still decided to follow the naming practice of Apple's official Frameworks, and to use the same for everything.

I have no strong opinion here. If you want I'll switch to `accountId`

2024-08-20 22:09 UTC, tmolitor-stud-tu commented
Okay, lets use somethingID then. Your reasoning makes sense here :)

Am 20. August 2024 23:55:19 MESZ schrieb lissine0 ***@***.***>:
>> Didn't we settle with `accountId` instead of `accountID`? I'm a bit unsure because we switched that back and forth while discussing. It could well be that I'm mistaken, of course.
>
>We did when we found out that `accountId` is used more in the codebase than `accountID`
>But I was curious what Apple uses. And I learned that in their frameworks (Foundation, SwiftUI), >90% of the time they use Identifier. But when they don't, they use ID.
>Examples: [1](https://developer.apple.com/documentation/foundation/nsdictionary/1412281-fileowneraccountid) [2](https://developer.apple.com/documentation/swiftui/scrollposition/viewid) [3](https://developer.apple.com/documentation/swiftui/tabviewcustomization/subscript(sectionid:)) [4](https://developer.apple.com/documentation/foundation/nsxmlparser/1411917-systemid?language=objc) [5](https://developer.apple.com/documentation/foundation/nsxmlparser/1411917-systemid?language=objc)
>
>However, I also discovered that in some of their WWDC swift code examples, they used [bookId](https://developer.apple.com/videos/play/wwdc2022/10061/) and [recipeId](https://developer.apple.com/videos/play/wwdc2022/10054/), and in some they used [uniqueID](https://developer.apple.com/videos/play/wwdc2024/10185/).
>But bookId was a local closure parameter, and recipeID was the argument to the defintion of a subscript.
>I guess they used fooId for local variables, and barID for anything viewable from outside the class.
>But I still decided to follow the naming practice of Apple's official Frameworks, and to use the same for everything.
>
>I have no strong opinion here. If you want I'll switch to `accountId`
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/1208#issuecomment-2299829624
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

2024-08-24 18:06 UTC, tmolitor-stud-tu commented
I will wait for the merge of Vaidik's media gallery before merging this.

I think you'll have to add some more commits to rename stuff after that Pr got merged. I'll merge this once that additional renaming is done, too.

2024-08-29 03:29 UTC, tmolitor-stud-tu commented
The gallery is merged now. Let me know once you fixed the conflicts and did the additional renaming and I'll merge the PR :)

2024-08-29 20:03 UTC, tmolitor-stud-tu requested changes
one small thing :)

2024-08-29 20:03 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +        } else if affiliation == kMucAffiliationProfile {
Could you rename "profile" and "reinvite" to something making clear that this is not a normal XEP-0045 affiliation? Maybe `kMucActionShowProfile` and `kMucActionReinvite`

2024-08-29 21:42 UTC, merged