Set monalGreen as the app's accent color
monal-im/Monal pull request #1218
Opened 2024-08-27 17:21 UTC by lissine0

Pick monalGreen as accent color for the entire app. This means that all the navigation UI elements, and most buttons would be colored in it (instead of our current mix between monalGreen and blue)
Also, it adapts to dark mode on its own. (two variants are provided, and SwiftUI selects the relevant one based on context)
In addition, macOS users will be able to customize the accent color from their OS settings. But by default they get monalGreen. (previously they could also customize it, but some UI elements didn't get overrided by their choice)

Note that I did not apply the accentColor to the Rich Alert's buttons, as it wasn't applied before, and I didn't know if you want it.

I also added a custom button style, that's used mostly in the Quicksy registration (but also the Add account button, and in Onboarding)
Be sure to check out its look in dark & light mode, when it's disabled and enabled.
(I made the text of the button only bold when it's enabled, and I changed the text's color from always white, to matching the background color, in an attempt to improve constrast in dark mode)

How the button style looks in various pages of the Quicksy registration:
(Note: some of these may be blurry)

<img src="https://github.com/user-attachments/assets/e49f3b29-af1a-41ad-894a-e07edb395396" width="270" height="480">
<img src="https://github.com/user-attachments/assets/fe670a2e-3e92-43f9-8471-e665bc3572cd" width="270" height="480">
<img src="https://github.com/user-attachments/assets/bd1c6c21-685a-4169-a658-53d7a9c8a0f3" width="270" height="480">
<img src="https://github.com/user-attachments/assets/1eef0c4d-e8c0-4c20-bb14-d77a66aee0b2" width="270" height="480">
 <img src="https://github.com/user-attachments/assets/fef92bd9-e0c0-4adb-99b6-20652b05dbee" width="270" height="480">
<img src="https://github.com/user-attachments/assets/0308e2c2-2462-415a-89e7-bb21cf4527e9" width="270" height="480">
<img src="https://github.com/user-attachments/assets/0c3dc084-58fe-4fb0-9c2b-3cb84d60e8dd" width="270" height="480">
<img src="https://github.com/user-attachments/assets/64637133-e3ed-4ad5-908c-3e93f68d0616" width="270" height="480">
<img src="https://github.com/user-attachments/assets/c85acdaf-9c34-497f-a516-b68f09a6f2f4" width="270" height="440">
<img src="https://github.com/user-attachments/assets/d41f0135-137b-4f6c-ba9b-a863c07e2b23" width="270" height="440">

On a semi-related note, in the ContactDetails, there's an option to select when you should receive notifications (always, on mention, and never)
A ring bell gets colored accordingly in each case.
But the entire list entry is by default colored in the accentColor, because the entire entry is a button that's not a navigation link.

<img src="https://github.com/user-attachments/assets/f5d84c2b-ab38-4ae9-8dfd-bc0255d17926" width="270" height="480">
<img src="https://github.com/user-attachments/assets/795648e8-834d-498d-9abe-ac01dae7f5ee" width="270" height="480">
<img src="https://github.com/user-attachments/assets/b72c22ff-459d-4d1b-b2ba-7babe607e43b" width="270" height="480">

I'm not sure how we should do in this case with regard to stying. Should the color of the list entry match the color of the ring bell? Or would a red color imply something rather strong to the user? (i.e. it might give the idea it's dangerous or destructive).
We could also change it to the primary color; or keep it as it is now.
(side question: when it is set to on-mention, should it be black or in the accent color?)

There's also another entry below it that's colored in the accent Color ("show shared Media and Files")
Just like the other one, It is in the accent color by default because it's a button that's not a navigation link.
I think it should be in primary color like the other entries, but I didn't modify it.

2024-08-27 19:09 UTC, lissine0 commented
For the sake of comparison, here's how the button style looks like with white text in dark mode


<img alt="" width="270" height="480" src="https://github.com/user-attachments/assets/cb68cb1d-da2d-464c-9178-a7d37853a653"/>

(I thought it a little hard on the eyes)

2024-08-27 19:32 UTC, tmolitor-stud-tu commented
I like the new `MonalProminentButtonStyle`very much :) And the design looks good, too :)

Two questions:
- could you use the 2 green values of the quicksy icon as the two monalGreen values for the quicksy build flavor
- what do you mean by the richAlert buttons you did not change? Do you have a screenshot of these buttons?

2024-08-27 19:33 UTC, tmolitor-stud-tu commented
See here for the 2 quicksy colors (the 2 green colors in the background): https://github.com/monal-im/Monal/blob/develop/Monal/Images.xcassets/QuicksyAppLogo.imageset/Quicksy-ios-1024.png

2024-08-27 20:03 UTC, tmolitor-stud-tu commented
Regarding your other questions: I think the bell icon should be colored, but the text beneath it should be primary. The icon should be green/black/red (always/mention/never)...but I'd use normal green like the one used by ios for the switch below.

regarding the media button: that one should be primary, too.

regarding your last dark mode screenshot: why is the text of that button in white? shouldn't it be in black like in your other quicksy screenshots?

2024-08-27 21:40 UTC, lissine0 commented
> I like the new `MonalProminentButtonStyle`very much :) And the design looks good, too :)

glad you liked it :)


> what do you mean by the richAlert buttons you did not change? Do you have a screenshot of these buttons?

I did not change the RichAlert at all. (and its buttons weren't automatically colored by SwiftUI)
Here's how it looks: (the same as before the PR)


<img width="270" height="480" src="https://github.com/user-attachments/assets/218281f1-9e6a-4bb2-bdcc-ef0324cb970f">
<img width="270" height="480" src="https://github.com/user-attachments/assets/6c8fa4e2-2a15-4255-9632-8e0d2446dd6f">


> regarding your last dark mode screenshot: why is the text of that button in white? shouldn't it be in black like in your other quicksy screenshots?

That's from an old version of my code. I posted it to demonstrate why I had to change the style of the button. (before this PR, the text on the button was always white, regardless of dark / light mode. It looked fine back then because its background was blue)

2024-08-27 23:09 UTC, lissine0 commented
FYI, in Quicksy's logo, the left side has a constant color, wherease the right side has variable brightness.
I took the RGB value from the heads of the two people on the right (R: 102, G: 185, B: 105, A: 1.0)

![Screenshot](https://github.com/user-attachments/assets/5ece7684-93f3-4cca-991e-964b19137880)

2024-08-28 05:15 UTC, tmolitor-stud-tu commented
> That's from an old version of my code. I posted it to demonstrate why I had to change the style of the button.

Ah! Everything alright then :)

The quicksy colors you picked are okay, too :)

I guess this PR can be merged after you fixed the current conflicts (sorry for creating them) and finished the quicksy coloring :)

2024-08-28 05:21 UTC, tmolitor-stud-tu requested changes
Some small things to change

2024-08-28 05:21 UTC, tmolitor-stud-tu commented on Monal/Classes/RegisterAccount.swift
> +                            .buttonStyle(.bordered)
Why did you change this to bordered? I believe this make a tap somewhere in the same row trigger the button, even if not tapped onto the button at all. I'm not sure if that's intended here.

2024-08-28 05:21 UTC, tmolitor-stud-tu commented on Monal/Classes/WelcomeLogIn.swift
> +                                .buttonStyle(.bordered)
Why did you change this to bordered? I believe this make a tap somewhere in the same row trigger the button, even if not tapped onto the button at all. I'm not sure if that's intended here.

2024-08-28 05:21 UTC, tmolitor-stud-tu commented on Monal/shareSheet-iOS/ShareViewController.m
> +    UIColor* monalDarkGreen = [UIColor colorWithRed:20.0/255 green:138.0/255 blue:103.0/255 alpha:1.0f];
Why did you duplicate the color codes in here? Please don't do this, if possible.

(On the other hand: if we replace this whole UI with a SwiftUI rewrite soon, this might be okay)

2024-08-28 16:15 UTC, lissine0 commented on Monal/Classes/RegisterAccount.swift
> +                            .buttonStyle(.bordered)
> I believe this make a tap somewhere in the same row trigger the button, even if not tapped onto the button at all.

I reversed this change.
But just as an FYI, this also happens now / before my PR, but it's not noticeable because there's very small horizontal space next to the button.

2024-08-28 16:19 UTC, lissine0 commented on Monal/shareSheet-iOS/ShareViewController.m
> +    UIColor* monalDarkGreen = [UIColor colorWithRed:20.0/255 green:138.0/255 blue:103.0/255 alpha:1.0f];
Resolved by adding `shareSheet` to the target membership of `Images.xcassets`

2024-08-29 00:17 UTC, merged