Rewrite the ServerDetails view in SwiftUI
monal-im/Monal pull request #1228
Opened 2024-09-03 16:42 UTC by lissine0

Replicate the UI of the UIKit version.

2024-09-03 16:43 UTC, lissine0 commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirstWithNoVarArgs:(NSString* _Nonnull) queryString;
I'm open to suggestions for better names to the added functions

2024-09-03 20:30 UTC, tmolitor-stud-tu requested changes

2024-09-03 20:30 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirstWithNoVarArgs:(NSString* _Nonnull) queryString;
`findFirst:`, `find:` and `check:` are all just wrappers for `-(NSArray*) find:(NSString* _Nonnull) queryString arguments:(va_list*) args` and that method should already be exported to swift as per https://developer.apple.com/documentation/swift/stringinterpolationprotocol

--> no need to change the objc side of things, just write 2 wrapper functions as a swift category of `MLXMLNode` (e.g. using the swift keyword `extension`).

2024-09-03 20:51 UTC, tmolitor-stud-tu requested changes

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +    func makeServerDetailsView(_ xmppAccount: xmpp) -> UIViewController {
```suggestion
    func makeServerDetailsView(for: xmppAccount: xmpp) -> UIViewController {
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +        case .success:
Coding style: indent the cases inside the switch statement

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +            Text(LocalizedStringKey(title))
I'm not sure if the system will manage to extract the localizable strings this way, use explicit `NSLocalizedString` to make sure that the title and description remain translatable.

Background: XCode has two methods for the extraction of localizable strings. One will compile the whole source tree and collect every usage of `LocalizedStringKey`, the other one only collecting the strings inside `Text()` (and a few others).

We can't use the first one, because it somehow throws an error. Feel free to try to fix this, though :)
See `scripts/updateLocalization.sh`, you can call it like this: `scripts/updateLocalization.sh NOCOMMIT YES` to try the compile variant (use `scripts/updateLocalization.sh NOCOMMIT` to try without compilation.

You'll have to install `bartycrouch` using homebrew first.

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +        }.navigationTitle(connection.identity.domain)
```suggestion
        }
        .navigationTitle(connection.identity.domain)
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    }
```suggestion
    guard connection.conferenceServers.count > 0 else {
        return [EntryData(title: "None",
                           description: "This server does not provide any MUC servers.",
                           status: .error)]
    }

    var result: [EntryData] = []
    for (jid, node) in (connection.conferenceServers as! [String: MLXMLNode]) {
        let entry = node.findFirstWithNoVarArgs("identity@@") as! [String: String]

        result.append(EntryData(title: "Server: \(jid)",
                                 description: "\(entry["name"]!) (type \(entry["type"]!), category \(entry["category"]!))",
                                 status: entry["type"] == "text" ? .success : .normal))
    }
    return result
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +        if (service["type"] == "stun" || service["type"] == "turn") {
wouldn't a switch statement with fallthrough cases be more elegant here?

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    result.append(EntryData(title: "None",
```suggestion
        result.append(EntryData(title: "None",
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    if xmppAccount.discoveredServersList.count == 0 {
Use a guard statement, too

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                foundCurrentConn = true
```suggestion
            if (xmppAccount.connectionProperties.server.connect() == hostname &&
                    xmppAccount.connectionProperties.server.connectPort() == port &&
                    xmppAccount.connectionProperties.server.isDirectTLS() == isSecure) {
                entryStatus = .success
                foundCurrentConn = true
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                foundCurrentConn = true
OR:
```suggestion
            if (xmppAccount.connectionProperties.server.connect() == hostname &&
            xmppAccount.connectionProperties.server.connectPort() == port &&
            xmppAccount.connectionProperties.server.isDirectTLS() == isSecure) {
                entryStatus = .success
                foundCurrentConn = true
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +            ]
```suggestion
    return [
        EntryData(
            title: "TLS 1.2",
            description: "Older, slower, but still secure TLS version",
            status: connection.tlsVersion == "1.2" ? .success : .normal
        ),
        EntryData(
            title: "TLS 1.3",
            description: "Newest TLS version which is faster than TLS 1.2",
            status: connection.tlsVersion == "1.3" ? .success : .normal
        ),
    ]
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    if connection.saslMethods.count == 0 {
Guard statement

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +            case "PLAIN":
Indendation

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                           status: .error)]
```suggestion
        return [
            EntryData(
                title: "None",
                description: "This server does not support any modern channel-binding to secure against MITM attacks on the TLS layer.",
                status: .error
            )
        ]
```

2024-09-03 20:51 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                           status: .error)]
OR:
```suggestion
        return [EntryData(
            title: "None",
            description: "This server does not support any modern channel-binding to secure against MITM attacks on the TLS layer.",
            status: .error
        )]
```

2024-09-04 01:35 UTC, lissine0 commented on Monal/Classes/ServerDetails.swift
> +                foundCurrentConn = true
what about:
```
        if xmppAccount.connectionProperties.server.connect() == hostname &&
           xmppAccount.connectionProperties.server.connectPort() == port &&
           xmppAccount.connectionProperties.server.isDirectTLS() == isSecure {
            entryStatus = .success
            foundCurrentConn = true
        } else if !foundCurrentConn {
```
Also, I assume it is for readability here that `xmppAccount.connectionProperties` was used in here instead of `connection` (and consequently that connection wasn't passed as an argument to the function; I followed https://github.com/monal-im/Monal/blob/2ce574b/Monal/Classes/MLServerDetails.m#L219)

2024-09-04 02:27 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                foundCurrentConn = true
What about this one? That's my favorite :)
```
            if (xmppAccount.connectionProperties.server.connect() == hostname &&
                xmppAccount.connectionProperties.server.connectPort() == port &&
                xmppAccount.connectionProperties.server.isDirectTLS() == isSecure
            ) {
                entryStatus = .success
                foundCurrentConn = true
```

Regarding readability: I don't know why `xmppAccount.connectionProperties` was used instead of `connection`. Feel free to change that if you want  :)

2024-09-04 02:33 UTC, tmolitor-stud-tu requested changes

2024-09-04 02:33 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    result.append(EntryData(title: "XEP-0163 Personal Eventing Protocol",
why use `result.append` instead of just listing every entry inside an array literal?

2024-09-04 02:33 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                                status: entry["type"] == "text" ? .success : .normal))
```suggestion
        result.append(EntryData(
            title: "Server: \(jid)",
            description: "\(entry["name"]!) (type \(entry["type"]!), category \(entry["category"]!))",
            status: entry["type"] == "text" ? .success : .normal
        ))
```

2024-09-04 02:33 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +        result.append(EntryData(title: service["type"] ?? "error",
same here (and multiple other places)

2024-09-04 02:44 UTC, lissine0 commented on Monal/Classes/ServerDetails.swift
> +                                status: entry["type"] == "text" ? .success : .normal))
Should I match it with the style I picked in https://github.com/monal-im/Monal/pull/1228#discussion_r1742676959 ? (when returning an array literal)

2024-09-04 02:56 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +                                status: entry["type"] == "text" ? .success : .normal))
yes :)

2024-09-04 17:56 UTC, tmolitor-stud-tu requested changes

2024-09-04 17:56 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
why that arbitrary empty line here?

2024-09-04 17:56 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
why that empty line?

2024-09-04 17:56 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +        result.append(EntryData(title: "Server: \(hostname)",
coding style

2024-09-04 17:56 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
why that empty line?

2024-09-04 17:56 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
why that empty line?

2024-09-04 21:05 UTC, lissine0 commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirstWithNoVarArgs:(NSString* _Nonnull) queryString;
See https://github.com/monal-im/Monal/compare/7b60a85..70faba9

2024-09-04 21:07 UTC, lissine0 commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirstWithNoVarArgs:(NSString* _Nonnull) queryString;
Or would you rather we do the computation in objective-C and just use the result in Swift?
I think it depends whether you expect to need check / findFirst in Swift in the future.

2024-09-04 21:17 UTC, lissine0 commented on Monal/Classes/ServerDetails.swift
> +
It's not so arbitrary, because all the following declarations depend on the first one.
But I'll remove it.

2024-09-04 22:11 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +            Text(LocalizedStringKey(title))
This has still to be solved. Why don't you just pass in `Text` views for title and description instead of strings? That would solve it without fixing the compilation problems I already mentioned.

2024-09-04 22:13 UTC, tmolitor-stud-tu requested changes

2024-09-04 22:13 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirst:(NSString* _Nonnull) queryString :(va_list) args;
Didn't we settle for moving all things needing a mlxml query to computed properties and removing all those mlxmlnode swift bridging stuff?

2024-09-05 01:03 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirstWithNoVarArgs:(NSString* _Nonnull) queryString;
I don't expect swift code to use the MLXMLNode at all. All processing should be kept in the objc land and only the UI should be in swift (or some small helpers not possible to write in objc)

2024-09-05 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMLNode.h
> +-(id _Nullable) findFirstWithNoVarArgs:(NSString* _Nonnull) queryString;
Objc land should expose models backed by db etc. to be used by swift (like the MLContact, MLMessage or MLContactSoftwareVersionInfo models)

2024-09-07 01:05 UTC, tmolitor-stud-tu requested changes

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPConnection.h
> +-(BOOL) supportsRosterVersioning;
no, I talked about a computed readonly property (having only a getter method), not a plain method

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +enum Status {
please make that enum fileprivate, to avoid name clashes

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +struct EntryData: Identifiable {
please either make this fileprivate, too, or rename it to `ServerDetailsEntryData`

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    let title: String
why do you replicate the contents of `EntryData` instead of making `EntryData` a `class` inheriting from `ObservableObject` and using it as `@ObservedObject var`

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    let status: Status
add a computed property named `color` using the `Status` to calculate the color

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +        switch status {
move that into the computed property above

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
why that empty line?

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    // Yes, conferenceServers is plural, but for now, our connectionProperties only store one single muc server (the first one encountered)
are you sure about that (only one single muc server)?

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    // Yes, conferenceServers is plural, but for now, our connectionProperties only store one single muc server (the first one encountered)
I've posted a screenshot in our dev muc showing the old objc interface listing multiple chatroom servers...

2024-09-07 01:05 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +private func getStunTurnEntryData(connection: MLXMPPConnection) -> [EntryData] {
why don't you add all these functions to the `ServerDetails` view?

2024-09-07 05:58 UTC, lissine0 commented on Monal/Classes/ServerDetails.swift
> +    // Yes, conferenceServers is plural, but for now, our connectionProperties only store one single muc server (the first one encountered)
I copied the comment from https://github.com/monal-im/Monal/blob/develop/Monal/Classes/MLServerDetails.m#L180
I didn't verify whether or not it was true 😅

2024-09-07 06:15 UTC, lissine0 commented on Monal/Classes/MLXMPPConnection.h
> +-(BOOL) supportsRosterVersioning;
Shall I keep the `conferenceServersInfo` a plain method?
I think doing so may be better for clarity, since there is already a `conferenceServers` property. (especially that one is a dictionary and the other is an array of dictionaries)

2024-09-07 06:59 UTC, lissine0 commented on Monal/Classes/ServerDetails.swift
> +    let title: String
Hmm, why not `let entryData: EntryData` (and make it a `@State` if you need to)?

2024-09-07 14:47 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +    let title: String
That would be possible, too...but structs have some limitations, classes don't have...therefore models should usually be classes

2024-09-07 14:51 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPConnection.h
> +-(BOOL) supportsRosterVersioning;
well, renaming `conferenceServers` to `conferenceServersDisco` and making `conferenceServersInfo` a computed property, too, would be even cleaner. what do you think?

2024-09-08 01:39 UTC, tmolitor-stud-tu requested changes
These are the last change requests, I guess :)

2024-09-08 01:39 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
Why that empty line between those 2 vars? Even the empty line below is strange, because these 2 vars belong to the for block after them.

2024-09-08 01:39 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
Why that empty line? The two vars belong to the for block below them.

2024-09-08 01:39 UTC, tmolitor-stud-tu commented on Monal/Classes/ServerDetails.swift
> +
Here again.

2024-09-08 06:47 UTC, lissine0 commented on Monal/Classes/MLXMPPConnection.h
> +-(BOOL) supportsRosterVersioning;
How about we keep `conferenceServers` as is, and we rename `conferenceServersInfo` to `conferenceServersIdentity` ?

2024-09-08 07:12 UTC, lissine0 commented on Monal/Classes/MLXMPPConnection.h
> +-(BOOL) supportsRosterVersioning;
or `conferenceServerIdentities`

2024-09-08 20:47 UTC, merged