Implement XEP-0157: Contact Addresses for XMPP Services
monal-im/Monal pull request #1238
Opened 2024-09-15 00:57 UTC by lissine0

<img alt="yax.im" width="270" height="480" src="https://github.com/user-attachments/assets/00863d4a-4059-4b67-932c-c3ab4cca41b3">
<img alt="conversations.im" width="270" height="480" src="https://github.com/user-attachments/assets/edef6688-f28c-4677-a0b0-5b95e5849c86">

2024-09-15 00:58 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    account.connectionProperties.serverContactAddresses = resultDictionary;
Is this fine? or is [ copy]  /  [ mutableCopy] more appropriate?

2024-09-15 01:04 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    //get the server's contact addresses (XEP-0157)
I considered moving this section to a separate handler, but I think there is no need to send two separate IQs that are identical. See [xmpp.m L3959-L3961](https://github.com/monal-im/Monal/blob/develop/Monal/Classes/xmpp.m#L3959-L3961)

2024-09-15 01:05 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    NSString* fieldName;
Side question: would it be more efficient if NSMutableString is used here?

2024-09-15 22:09 UTC, tmolitor-stud-tu requested changes

2024-09-15 22:09 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    for (MLXMLNode* field in dataForm.children)
Read the data-forms part of my xml query article and check out the disctionary and array interfaces in XMPPDataForm.h as well.

2024-09-15 22:09 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    account.connectionProperties.serverContactAddresses = resultDictionary;
having this non-mutable would be better...

2024-09-15 22:09 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    NSString* fieldName;
use NSMutableString where?

2024-09-15 22:09 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    //get the server's contact addresses (XEP-0157)
no, sending two iqs would be just stupid, your solution to add it here is great :)

2024-09-16 05:02 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    NSString* fieldName;
`NSMutableString* fieldName;` instead of `NSString* fieldName;`

2024-09-16 06:20 UTC, lissine0 commented on Monal/Classes/MLIQProcessor.m
> +    account.connectionProperties.serverContactAddresses = resultDictionary;
So do you mean just
`account.connectionProperties.serverContactAddresses = [resultDictionary copy];`

Or do you also mean changing `MLXMPPConnection.serverContactAddresses`'s type from `NSMutableDictionary*` to `NSDictionary*`

2024-09-25 00:40 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    account.connectionProperties.serverContactAddresses = resultDictionary;
both, copy and change to NSDictionary

2024-09-25 00:42 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    NSString* fieldName;
but the field name isn't mutated at all, why use NSMutableString? You'd even have to mutably copy the NSString over into an NSMutableString as opposed to just using the NSString directly as is.

2024-09-26 00:47 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +    for (MLXMLNode* field in dataForm.children)
This still needs to be addressed...

2024-09-29 00:08 UTC, tmolitor-stud-tu commented
quick heads up: this is still missing the dataforms rewrite to be mergeable...

2024-10-05 20:19 UTC, lissine0 commented
Just as an FYI:

- the `%fieldName` extraction command doesn't work: it doesn't have any effect.
For example, `[iqNode findFirst:@"{http://jabber.org/protocol/disco#info}query/\\{http://jabber.org/network/serverinfo}result%%admin-addresses\\"];` returns the whole dataForm, as if `%%admin-addresses` wasn't there.
On the other hand, XMPPDataForm's `getField:(NSString*) name` works; and the `@fieldName` extraction command works.

 And

- XMPPDataForm's `objectAtIndexedSubscript:(NSInteger) idx` doesn't work.
In fact trying `[dataForm objectAtIndexedSubscript:0];` causes an exception: `Exception  NSException *   "*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty array"`, eventhough the server does have published contact addresses.
XMPPDataForm.h does have a [comment](https://github.com/monal-im/Monal/blob/8f0a624/Monal/Classes/XMPPDataForm.h#L38) above the method signature, saying the interface is incomplete, so I assume this is expected.

2024-10-06 18:00 UTC, tmolitor-stud-tu commented
Why did you double the `%`? You were qurying for the field `%admin-addresses` which indeed isn't there.

But why use the `%` operator at all? That will return a dictionary with additional information, but you'll only need the field value, so the `@` operator should be enough...

2024-10-06 18:02 UTC, tmolitor-stud-tu commented
`objectAtIndexedSubscript` will only work for data-forms having multiple item elements encapsulating the form fields, see [example 8 of XEP-0004](https://xmpp.org/extensions/xep-0004.html#example-8).

2024-10-06 18:03 UTC, tmolitor-stud-tu commented
No, the "incomplete interface" comment means that it does not implement everything an `NSArray` or `NSDictionary` is capable of.

2024-10-06 21:58 UTC, lissine0 commented
> Why did you double the `%`? You were qurying for the field `%admin-addresses` which indeed isn't there.

%% is needed to escape the % inside the string, otherwise it'll be looking for a conversion format (%@, %d etc.)
It's the same reason there are double slashes.

> But why use the `%` operator at all?

I don't need it in this case. I was just trying different things.

2024-10-06 22:57 UTC, tmolitor-stud-tu commented
ah, this is a interference between the `NS_FORMAT_FUNCTION` annotation (triggering compiler errors for incorrectly used format specifiers) of the `find:` method and the query implementation not allowing a format specifier at that position but using it as an "ordinary" extraction operator...

I'll fix that and use another operator instead of `%`, but the `@` should still work just fine.

2024-10-08 21:19 UTC, lissine0 commented
I tested eb680c6f1 and the `&` extraction command works correctly

2024-10-09 04:28 UTC, merged