Integrate "Add Account (advanced)" in WelcomeLogIn.swift
monal-im/Monal pull request #1246
Opened 2024-09-21 15:48 UTC by lissine0

<img src="https://github.com/user-attachments/assets/1a71ae8b-e857-401f-a973-b0a4be46a5dd" width="270" height="480">
<img src="https://github.com/user-attachments/assets/d3d7dadc-3e2c-4b85-9439-6c0bb818342a" width="270" height="480">

2024-09-25 01:04 UTC, tmolitor-stud-tu commented
I don't like this. the welcome login screen should be easy to use for non-techies and advanced options should be hidden in a separate screen for tech savy people to use.

2024-09-25 04:53 UTC, lissine0 commented
> the welcome login screen should be easy to use for non-techies and advanced options should be hidden in a separate screen for tech savy people to use.

That's exactly how it is in this PR. The screenshots above are what's shown when `Add Account (advanced)` is selected from the settings. Normal `Add Account` is still the same as before.

What this PR does, is basing `Add Account (advanced)` on `Add Account` instead of `Account Edit`
It feels more natural this way.

2024-09-25 22:23 UTC, tmolitor-stud-tu commented
Ah okay, that's okay. But, for the advanced view, could you remove the logo and change the explanatory text at the top to something explaining that this is an advanced expert account creation menu?

2024-09-25 22:25 UTC, tmolitor-stud-tu commented
We should make the direct tls switch only accessible (e.g. enabled) if the hostname or port fields contain something...

2024-10-06 06:08 UTC, lissine0 commented
> Ah okay, that's okay. But, for the advanced view, could you remove the logo and change the explanatory text at the top to something explaining that this is an advanced expert account creation menu?

Which one of these looks do you prefer? this:

<img src="https://github.com/user-attachments/assets/40773ef3-0fa9-4f65-b430-a35f547096fc" width="270" height="480">
<img src="https://github.com/user-attachments/assets/b9c82397-a3a0-4c61-8186-16082693965b" width="270" height="480">

Or:

<img src="https://github.com/user-attachments/assets/b1ee5f0c-6904-47f0-aab4-39022d18ccb9" width="270" height="480">
<br></br>

> We should make the direct tls switch only accessible (e.g. enabled) if the hostname or port fields contain something...

Would you like to also switch the toggle to `false` if the user types something in hostname / port, then enables directTLS, then clears the hostname / port?

2024-10-06 18:05 UTC, tmolitor-stud-tu commented
I'd prefer the third one. @FriedrichAltheide @matthewrfennell what do you prefer?

> Would you like to also switch the toggle to false if the user types something in hostname / port, then enables directTLS, then clears the hostname / port?

I'd say yes.

2024-10-06 19:16 UTC, matthewrfennell commented
> I'd prefer the third one. @FriedrichAltheide @matthewrfennell what do you prefer?

I agree

2024-10-06 22:59 UTC, tmolitor-stud-tu commented
okay, third one it is :)

2024-10-09 05:14 UTC, tmolitor-stud-tu requested changes
Almost mergeable :)

2024-10-09 05:14 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPManager.m
> +return [self login:jid password:password hardcodedServer:nil hardcodedPort:nil forceDirectTLS:NO allowPlainAuth:plainActivated];
wrong indentation.

2024-10-09 05:14 UTC, tmolitor-stud-tu commented on Monal/Classes/WelcomeLogIn.swift
> +                                TextField("Optional Port", text: $hardcodedPort)
should be "Optional Hardcoded Port" (the "hardcoded" is missing)

2024-10-09 05:14 UTC, tmolitor-stud-tu commented on Monal/Classes/WelcomeLogIn.swift
> +                                Toggle(isOn: $allowPlainAuth){
could you add a list of domains for which this toggle isn't allowed to be turned on? that list should currently only contain "conversations.im", but more might be added.

2024-10-14 11:24 UTC, tmolitor-stud-tu requested changes

2024-10-14 11:24 UTC, tmolitor-stud-tu commented on Monal/Classes/WelcomeLogIn.swift
> +                                Toggle(isOn: $allowPlainAuth){
@lissine0  this seems still to be missing, right?

2024-10-16 22:34 UTC, lissine0 commented
I made some other changes aside from those you asked for. Here's a demo of them:

https://github.com/user-attachments/assets/11b97e74-cb73-4d77-8ae4-3484cb669747

The reason why I did this is: the hardcoded port is only used in connection if a hardcoded server is set.
And I think the forceDirectTLS setting is also only used if there's a hardcoded server.
Thus I made the UI changes to make the users aware that those settings only take effect when setting a hardcoded server.

Also, in the old UI, 5222 is set by default as hardcoded port, even when doing a normal account adding. That can confuse users into thinking that StartTLS is used because of that value.
Thus I made 5222 the default only when a hardcoded server is set. Otherwise an empty string is used.
(We can store an empty string in a DB column of type Int because of a quirk in SQLite: the column's type is just a hint, and it doesn't prevent us from from storing a string in an int column)

And BTW, you were correct, the old add account (advanced) did indeed disallow plain auth for conversations.im
(XMPPEdit.m L342)

2024-10-18 11:03 UTC, tmolitor-stud-tu approved these changes

2024-10-18 11:03 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.m
> +            nilDefault(server, @""),
I like that you are using the `nilDefault` macro :)

2024-10-18 11:03 UTC, merged