Create AppStoreDescrition
monal-im/Monal pull request #500
Opened 2020-10-15 21:10 UTC by Echolon

I worked over the text a little bit. Will expand the XEPs by time.

2021-01-04 19:29 UTC, eeeeeta requested changes

2021-01-04 19:29 UTC, eeeeeta commented on AppStoreDescrition
> +Monal is a fast and user friendly way to use the decentral XMPP protocol (known as Jabber). Just download the app, login or register and you are ready
nit: `decentral` -> `decentralized`

2021-01-04 19:29 UTC, eeeeeta commented on AppStoreDescrition
> +The software is availbale on iOS and MacOS.
nit: `available`

2021-01-04 19:29 UTC, eeeeeta commented on AppStoreDescrition
> +Monal implements XEP modules and extensions to ensure an enjoying mobile communication experience:
nit: `enjoying` -> `enjoyable`

2021-01-04 20:45 UTC, Echolon commented on AppStoreDescrition
> +Monal implements XEP modules and extensions to ensure an enjoying mobile communication experience:
Thank you for reviewing!

2021-01-23 18:19 UTC, Echolon commented
Hi Anu,

may you merge it and put it to the App Store description?

2021-02-05 22:09 UTC, anurodhp approved these changes

2021-02-05 22:09 UTC, merged

2021-02-05 23:05 UTC, Echolon commented
@anurodhp please do not forget to also update in the App store (or automate this pull if possible)