Update status and remove version
monal-im/Monal pull request #557
Opened 2021-02-06 13:29 UTC by Echolon

@wurstsalat3000

The only thing I don't understand yet:

- All namespaces should go in rdf:RDF

2021-02-07 10:43 UTC, wurstsalat3000 commented
I *think* this is how it should look like:
```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:xmpp="https://linkmauve.fr/ns/xmpp-doap#"
        xmlns="http://usefulinc.com/ns/doap#"
        xmlns:schema="https://schema.org/" 
  <Project>
```
Additional note: git repository location also points to the old URL.

2021-02-07 11:15 UTC, Echolon commented
Thank you @wurstsalat3000

2021-02-08 16:59 UTC, tmolitor-stud-tu commented
@Echolon can you extract a list of XEPs that are marked "planned", I want to check if this lists something we are not planning to do...

2021-02-08 21:02 UTC, Echolon commented
> @Echolon can you extract a list of XEPs that are marked "planned", I want to check if this lists something we are not planning to do...

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0027: Current Jabber OpenPGP Usage</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0033: Extended Stanza Addressing</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0047: In-Band Bytestreams</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0048: Bookmarks</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0054: vcard-temp</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0055: Jabber Search</xmpp:note>  

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0065: SOCKS5 Bytestreams</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0070: Verifying HTTP Requests via XMPP</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0107: User Mood</xmpp:note> 

        <xmpp:xep rdf:resource="https://xmpp.org/extensions/xep-0153.html" />
        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0153: vCard-Based Avatars</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0215: External Service Discovery</xmpp:note>  

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0234: Jingle File Transfer</xmpp:note> 

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0249: Direct MUC Invitations</xmpp:note> 

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0261: Jingle In-Band Bytestreams Transport 

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0308: Last Message Correction</xmpp:note> 

        <xmpp:status>complete</xmpp:status>
        <xmpp:note>XEP-0357: Push Notifications</xmpp:note> 

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0369: Mediated Information eXchange (MIX)</xmpp:note> 

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0374: OpenPGP for XMPP Instant Messaging</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0377: Spam Reporting (via XEP-0191)</xmpp:note>

        <xmpp:xep rdf:resource="https://xmpp.org/extensions/xep-0379.html" />
        <xmpp:status>planned</xmpp:status>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0380: Explicit Message Encryption</xmpp:note>   

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0386: Bind 2.0</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0390: Entity Capabilities 2.0</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0392: Consistent Color Generation</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0396: Jingle Encrypted Transports - OMEMO</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0397: Instant Stream Resumption</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0402: PEP Native Bookmarks</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0409: IM Routing-NG</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0410: MUC Self-Ping (Schrödinger's Chat)</xmpp:note>

        <xmpp:status>planned</xmpp:status>
        <xmpp:note>XEP-0420: Stanza Content Encryption</xmpp:note>

2021-02-14 14:32 UTC, tmolitor-stud-tu commented
That are many "planned" that are not really planned

2021-02-14 15:36 UTC, tmolitor-stud-tu commented
planned is only:
```

<xmpp:status>planned</xmpp:status>
<xmpp:note>XEP-0048: Bookmarks</xmpp:note>

<xmpp:status>planned</xmpp:status>
<xmpp:note>XEP-0215: External Service Discovery</xmpp:note>  

<xmpp:status>planned</xmpp:status>
<xmpp:note>XEP-0249: Direct MUC Invitations</xmpp:note>

<xmpp:status>planned</xmpp:status>
<xmpp:note>XEP-0402: PEP Native Bookmarks</xmpp:note>
```

this is already implemented:

```
<xmpp:status>complete</xmpp:status>
<xmpp:note>XEP-0308: Last Message Correction</xmpp:note>
```

2021-02-17 21:41 UTC, Echolon commented
Ready for review

2021-02-20 16:43 UTC, tmolitor-stud-tu requested changes

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
> +        <xmpp:status>planned</xmpp:status>
not planned and never was

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
> +        <xmpp:status>partial</xmpp:status>
now complete in version 5.0

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
> +        <xmpp:status>wontfix</xmpp:status>
sorry, this is implemented

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
> +        <xmpp:status>wontfix</xmpp:status>
could be planned, too...but far into the future

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
> +        <xmpp:status>wontfix</xmpp:status>
could be planned, too...but far into the future

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
>          <xmpp:note>XEP-0379: Pre-Authenticated Roster Subscription</xmpp:note>
partial

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
> +        <xmpp:status>wontfix</xmpp:status>
planned

2021-02-20 16:43 UTC, tmolitor-stud-tu commented on monal.doap
>          <xmpp:note>XEP-0392: Consistent Color Generation</xmpp:note>
planned

2021-02-20 17:01 UTC, Echolon commented
Added changes

2021-02-20 17:05 UTC, tmolitor-stud-tu requested changes

2021-02-20 17:05 UTC, tmolitor-stud-tu commented on monal.doap
>          <xmpp:note>XEP-0191: Blocking Command. Partly, missing sync with server which accounts are blocked.</xmpp:note>
please remove the partly... part in the description

2021-02-20 17:25 UTC, Echolon commented on monal.doap
>          <xmpp:note>XEP-0191: Blocking Command. Partly, missing sync with server which accounts are blocked.</xmpp:note>
Done

2021-02-20 19:10 UTC, tmolitor-stud-tu approved these changes

2021-02-20 19:10 UTC, merged