Audio Recoder and other minor fix.
monal-im/Monal pull request #584
Opened 2021-02-26 10:24 UTC by poormusic2001

1. Add Audio Recoder and its Simple UI.
2. Add file-attatchment.imageset back.

2021-02-26 13:27 UTC, FriedrichAltheide requested changes

2021-02-26 13:27 UTC, FriedrichAltheide commented on Monal/Classes/MLAudioRecoderManager.m
> +        DDLogError(@"Audio Recoder set category error: %@", audioSessionCategoryError);
show warning to user? self.recoderManagerDelegate notifyResult:NO

2021-02-26 13:27 UTC, FriedrichAltheide commented on Monal/Classes/MLAudioRecoderManager.m
> +                                   [NSNumber numberWithFloat:32000.0], AVSampleRateKey, nil];
@tmolitor-stud-tu what do you think about the sample rate?

2021-02-26 13:27 UTC, FriedrichAltheide commented on Monal/Classes/MLAudioRecoderManager.m
> +        [self.recoderManagerDelegate notifyResult:YES error:@""];
can't you send "error:nil"?

2021-02-26 13:27 UTC, FriedrichAltheide commented on Monal/Classes/chatViewController.m
> +        [self.sendButton setImage:[UIImage systemImageNamed:@"mic"] forState:UIControlStateNormal];
I would prefer a separate button for the mic action that would only be visible if `chatInput.length == 0`

2021-02-26 14:46 UTC, Echolon commented
> 1. Add Audio Recoder and its Simple UI.
> 2. Add file-attatchment.imageset back.

Does this close #238 ?

2021-03-02 06:20 UTC, poormusic2001 commented
@FriedrichAltheide 

Add another commit. 
I modify the the empty string to nil and also add another button for record button.

2021-03-04 15:22 UTC, FriedrichAltheide reviewed
@Echolon #238 should be kept open. The inline Audio UI needs a bit more love...

2021-03-04 15:22 UTC, FriedrichAltheide commented on Monal/Classes/chatViewController.m
> +@property (atomic) BOOL isAudioMessage;
you never seem to be reading `isAudioMessage`

2021-03-04 15:22 UTC, FriedrichAltheide commented on Monal/Classes/chatViewController.m
> +                    UIAlertController *messageAlert =[UIAlertController alertControllerWithTitle:NSLocalizedString(@"Please Allow Audio Access",@ "") message:NSLocalizedString(@"If you want to use au
`, @"")`

2021-03-04 15:25 UTC, merged