add exact version info (build time / build id) to about window #618
monal-im/Monal pull request #619
Opened 2021-04-12 14:59 UTC by poormusic2001

as title

1. Make version string in settingsViewController copyable (User can also copy in the about window of catalyst version).
2. Build a new about window in the catalyst version.

2021-04-13 05:18 UTC, FriedrichAltheide requested changes

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/HelperTools.m
> +        versionTxt = [NSString stringWithFormat:@"Alpha %@ (%s: %s UTC)", [infoDict objectForKey:@"CFBundleShortVersionString"], __DATE__, __TIME__];
Please declare versionTxt here

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/HelperTools.m
> +        versionTxt = [NSString stringWithFormat:@"%@ (%@)", [infoDict objectForKey:@"CFBundleShortVersionString"], [infoDict objectForKey:@"CFBundleVersion"]];
and here

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/MLSettingsTableViewController.m
> +                versionTxt = [HelperTools appBuildVersionInfo];
`NSString* versionTxt = [...` use one line

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/MLSettingsTableViewController.m
> +                    UIPasteboard *pastboard = UIPasteboard.generalPasteboard;
code style

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/MLSettingsAboutViewController.m
> +    NSString *versionTxt = [HelperTools appBuildVersionInfo];
code style

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/MLSettingsAboutViewController.m
> +    UITapGestureRecognizer *tapReCognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(copyTxt:)];
code style

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/MonalAppDelegate.m
> +        UIKeyCommand *deleteCommand = [UIKeyCommand commandWithTitle:@"Delete Conversation" image:nil action:@selector(deleteConversation) input:@"\b" modifierFlags:UIKeyModifierCommand propertyList:
code style

2021-04-13 05:18 UTC, FriedrichAltheide commented on Monal/Classes/MonalAppDelegate.m
> +-(void) aboutWindow {
code style

2021-04-13 06:48 UTC, FriedrichAltheide requested changes

2021-04-13 06:48 UTC, FriedrichAltheide commented on Monal/Classes/HelperTools.h
> ++(NSString*)appBuildVersionInfo;
code style

2021-04-13 06:48 UTC, FriedrichAltheide commented on Monal/Classes/MLSettingsAboutViewController.m
> +    UITapGestureRecognizer* tapReCognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(copyTxt:)];
Why don't you setup the tap gesture for the version label in the storyboard?

2021-04-13 06:48 UTC, FriedrichAltheide commented on Monal/Classes/MLSettingsAboutViewController.m
> +- (NSArray<UIKeyCommand *>*)keyCommands {
code style

2021-04-14 09:46 UTC, poormusic2001 commented on Monal/Classes/MLSettingsAboutViewController.m
> +    UITapGestureRecognizer* tapReCognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(copyTxt:)];
1. I prefer to setup tap gesture in code.
2. Put many things in storyboard will load a very long time in my MacBook Air, like the Main.Storyboard.

So, I setup the tap gesture for the version label in the code. You can change it to the storyboard if you insist.

2021-04-26 10:50 UTC, merged