Fix issue #614
monal-im/Monal pull request #624
Opened 2021-04-13 09:23 UTC by poormusic2001

as title

Fix issue #614

Catalyst: custom background not shown after launch of monal #614

2021-04-13 10:43 UTC, FriedrichAltheide requested changes

2021-04-13 10:43 UTC, FriedrichAltheide commented on Monal/Classes/MLPlaceholderViewController.h
> +@property (weak, nonatomic) IBOutlet UIImageView* backgroundImageView;
Does it need to be public?

2021-04-13 10:43 UTC, FriedrichAltheide commented on Monal/Classes/MLPlaceholderViewController.m
> +    [nc addObserver:self selector:@selector(updateBackground) name:kMonalBackgroundChanged object:nil];
corresponding removeObserver is missing

2021-04-13 10:43 UTC, FriedrichAltheide commented on Monal/Classes/MLPlaceholderViewController.m
> +-(void) updateBackground {
code style

2021-04-13 10:43 UTC, FriedrichAltheide commented on Monal/Classes/MLPlaceholderViewController.m
> +    if(backgrounds){
code style (all if)

2021-04-13 10:43 UTC, FriedrichAltheide commented on Monal/Classes/MLPlaceholderViewController.m
> +        if(imageName)
I would prefer a debug assert if imageName is nil
@tmolitor-stud-tu "BackgroundImage" should always have a entry correct?

2021-04-13 10:43 UTC, FriedrichAltheide commented on Monal/localization/Base.lproj/Main.storyboard
> +                    <connections>
Please remove the current default image from the storyboard

2021-04-14 09:00 UTC, poormusic2001 commented on Monal/Classes/MLPlaceholderViewController.m
> +        if(imageName)
If imageName is nil, I let backgroundImageView to hide itself. 

So I add a else to hide the backgroundImageView.

2021-04-26 08:32 UTC, merged