Add donations and support chat information
monal-im/Monal pull request #643
Opened 2021-05-12 23:49 UTC by Echolon

2021-05-12 23:57 UTC, tmolitor-stud-tu commented on ReadMe.md
> +### www.monal.im
that is not a link but a heading!

2021-05-12 23:58 UTC, tmolitor-stud-tu commented on ReadMe.md
> +## monal@chat.yax.im
same a above...make this a link...ideally a ?join xmpp link (see the corresponding xep for the exact syntax)

2021-05-12 23:59 UTC, tmolitor-stud-tu commented on ReadMe.md
> +- For EU citizens you can ask the respective core developer for the IBAN number. Please contact Thilo Molitor via mail to thilo+monal@eightysoft.de
I wrote a better EU sentence

2021-05-13 00:03 UTC, Echolon commented on ReadMe.md
> +### www.monal.im
Yes, I wanted to increase the font size

2021-05-22 11:36 UTC, Echolon commented
Anything blocking a merge, apart from rebase? @tmolitor-stud-tu

2021-05-22 12:15 UTC, tmolitor-stud-tu commented
No

Am 22. Mai 2021 13:36:59 MESZ schrieb Echolon ***@***.***>:
>Anything blocking a merge, apart from rebase? @tmolitor-stud-tu 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/monal-im/Monal/pull/643#issuecomment-846395493

2021-05-23 04:05 UTC, tmolitor-stud-tu commented
git fetch origin
git checkout Echolon-update-ReadMe-20210513
git reset --hard origin/Echolon-update-ReadMe-20210513
git rebase -i origin/develop  # delete all commits in this list not coming from you
git push --force

2021-05-23 18:16 UTC, tmolitor-stud-tu requested changes

2021-05-23 18:16 UTC, tmolitor-stud-tu commented on ReadMe.md
> +### www.monal.im
No, make this a link so that it is clickable

2021-05-23 18:16 UTC, tmolitor-stud-tu commented on ReadMe.md
> +## xmpp:monal@chat.yax.im?join
Same here, make this a clickable link

2021-05-23 18:16 UTC, tmolitor-stud-tu commented on ReadMe.md
> +Find general information in the [Monal Wiki](https://github.com/monal-im/Monal/wiki).
Make sure there is a line break between these two lines (search Wikipedia on how to accomplish line breaks with markdown)

2021-05-24 11:31 UTC, tmolitor-stud-tu requested changes

2021-05-24 11:31 UTC, tmolitor-stud-tu commented on ReadMe.md
> +This is the Monal XMPP client as found in the app store.  If you want to  use the latest stable versions, search for Monal in the iOS or OSX app store. [Visit the blog to read about the development](
please make this link complete (including https)

2021-05-24 11:31 UTC, tmolitor-stud-tu commented on ReadMe.md
> +xmpp:monal@chat.yax.im?join
please make this a link:
`[monal@chat.yax.im](xmpp:monal@chat.yax.im?join)`

2021-07-20 08:53 UTC, tmolitor-stud-tu approved these changes

2021-07-20 08:53 UTC, merged