Bugfixes for 5.0 beta
monal-im/Monal pull request #668
Opened 2021-06-17 21:27 UTC by janst97

2021-06-17 21:32 UTC, tmolitor-stud-tu requested changes
no

2021-06-17 21:32 UTC, tmolitor-stud-tu commented on Monal/Classes/MLUploadQueueItem.m
> +    if(self = [super init])
[super init]mus ALWAYS be called and it has to be the first line in the init method (according to apple docs)

2021-06-17 21:32 UTC, tmolitor-stud-tu commented on Monal/Classes/MLUploadQueueItem.m
> +    if(self = [super init])
same here

2021-06-17 21:32 UTC, tmolitor-stud-tu commented on Monal/Classes/MLUploadQueueItem.m
> +    if(self = [super init])
why that if btw?

2021-06-17 21:32 UTC, tmolitor-stud-tu commented on Monal/Classes/MLUploadQueueItem.m
> +    if(self = [super init])
and again

2021-06-17 21:32 UTC, tmolitor-stud-tu commented on Monal/Classes/MLUploadQueueItem.m
> +    if(self = [super init])
[super init] will always return a non-nil value, no need to check it...

2021-06-17 21:38 UTC, janst97 commented on Monal/Classes/MLUploadQueueItem.m
> +    if(self = [super init])
I used this as reference: https://developer.apple.com/documentation/objectivec/nsobject/1418641-init?language=objc

"If the new object can’t be initialized, the method should return nil. For example, a hypothetical BuiltInCamera class might return nil from its init method if run on a device that has no camera.". However, this does not apply to NSObject, so it's not necessary here. I'll fix it.

2021-06-20 22:24 UTC, tmolitor-stud-tu approved these changes

2021-06-20 22:25 UTC, merged