Use SwiftUI to show notification settings
monal-im/Monal pull request #805
Opened 2022-05-03 21:52 UTC by janst97

2022-05-03 23:41 UTC, tmolitor-stud-tu commented on Monal/Classes/SwiftuiHelpers.swift
> +class SettingsSwiftInterface : NSObject {
that's nice, can you port the ContactDetailsInterface.makeContactDetails to this new class, too?

2022-05-03 23:55 UTC, tmolitor-stud-tu requested changes
overall a very good submission, for details, see my comments.

2022-05-03 23:55 UTC, tmolitor-stud-tu commented on Monal/Classes/NotificationSettings.swift
> +        .navigationTitle(Text(NSLocalizedString("Notifications", comment: "")))
You don't need to wrap literal text inside Text() into NSLocalizedString (you only need to wrap text that has dynamic components)

2022-05-03 23:55 UTC, tmolitor-stud-tu commented on Monal/Classes/NotificationSettings.swift
> +                            Text(NSLocalizedString("Apple push service should always be on. If it is off, your device can not talk to Apple's server.", comment: "")).font(.footnote)
see comment about Text() below

2022-05-03 23:55 UTC, tmolitor-stud-tu commented on Monal/Classes/NotificationSettings.swift
> +            return Label(labelText, systemImage: "checkmark.seal").accentColor(.green);
can you use an instance of `Text()` as `description` instead of making `description` a `String`?
That way you could remove the `isLocalized` argument completely.

2022-05-03 23:55 UTC, tmolitor-stud-tu commented on Monal/Classes/NotificationSettings.swift
> +                        }).alert(isPresented: $showPushToken) {
cool idea!

2022-05-03 23:55 UTC, tmolitor-stud-tu commented on Monal/Classes/NotificationSettings.swift
> +                AccountPushInfo(accountName: xmppAccount.connectionProperties.identity.jid, pushEnabled: xmppAccount.connectionProperties.pushEnabled)
why packaging those values into `AccountPushInfo` instead of just using the original `xmpp` object from `connectedXMPP`?

2022-05-04 10:55 UTC, janst97 commented on Monal/Classes/NotificationSettings.swift
> +                            Text(NSLocalizedString("Apple push service should always be on. If it is off, your device can not talk to Apple's server.", comment: "")).font(.footnote)
Does not work here because I want to change the font to footnote size.

2022-05-04 11:10 UTC, janst97 commented on Monal/Classes/NotificationSettings.swift
> +            return Label(labelText, systemImage: "checkmark.seal").accentColor(.green);
Label takes an argument that needs to conform to StringProtocol, which Text does not. But I moved the initialization of LocalizedString to the function call now. This way I don't need isLocalized too.

2022-05-04 11:14 UTC, tmolitor-stud-tu commented on Monal/Classes/NotificationSettings.swift
> +                            Text(NSLocalizedString("Apple push service should always be on. If it is off, your device can not talk to Apple's server.", comment: "")).font(.footnote)
Okay, but all other Text(nslocalizedstring()) occurrences should be fixed

2022-05-04 11:28 UTC, janst97 commented on Monal/Classes/NotificationSettings.swift
> +                            Text(NSLocalizedString("Apple push service should always be on. If it is off, your device can not talk to Apple's server.", comment: "")).font(.footnote)
Except for `navigationTitle` there are no other occurrences, either because I need `.font` or because alert does not take Strings.

2022-05-04 13:16 UTC, janst97 commented on Monal/Classes/NotificationSettings.swift
> +                            Text(NSLocalizedString("Apple push service should always be on. If it is off, your device can not talk to Apple's server.", comment: "")).font(.footnote)
I added a function for localized text to improve readability.

2022-05-04 16:50 UTC, tmolitor-stud-tu approved these changes

2022-05-04 16:51 UTC, merged