SwiftUI implementation of AddContact
monal-im/Monal pull request #870
Opened 2022-10-31 22:05 UTC by janst97

2022-11-01 05:07 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +    static private let jidFaultyPattern = "^.+@.+\\..{2,}$"
valid pattern?
isn't component.example.com a valid JID?

2022-11-12 15:05 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +                        MLContact.createContact(fromJid: jid, andAccountNo: accountNo) // FIXME Actually do something with it
TODO: Open contact

2022-11-12 15:05 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +                                Text("Import OMEMO fingerprints from QR code")
@tmolitor-stud-tu something that we have to do

2022-11-12 15:05 UTC, FriedrichAltheide commented on Monal/Classes/ContactRequestsMenu.swift
> +            Button {
Increase button size. e.g. in new line
Show animation notifying user about the action

2022-11-12 15:05 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +                        Picker("Use account", selection: $selectedAccount) {
only show account selection if more than one account is active
Maybe move jid selection in new line on small phones.

2022-11-12 15:05 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +                        Section(header: Text("A contact was scanned through the QR code scanner")) {
only show if qr code contains fingerprints

2022-11-12 15:05 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +                            Toggle(isOn: $importScannedFingerprints, label: {
"Import and trust"

2022-11-12 15:12 UTC, FriedrichAltheide commented on Monal/Classes/AddContactMenu.swift
> +                                Text("Don't add scanned contact")
Cancel + Add button same line, bigger buttons

2022-11-12 22:59 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +    static private let jidFaultyPattern = "^.+@.+\\..{2,}$"
yes it is, please fix

2022-11-12 23:00 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                                Text("Import OMEMO fingerprints from QR code")
@FriedrichAltheide yes, after merge

2022-11-12 23:24 UTC, tmolitor-stud-tu requested changes

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +    static private let jidFaultyPattern = "^.+\\..{2,}$"
`^([^@]+@)?.+\\..{2,}$`

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                                Text("Clear scanned contact")
Why not simply "Clear"?

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                    if(scannedFingerprints != nil && scannedFingerprints!.count > 1) {
why > 1 and not > 0?

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                            scannedFingerprints == nil ? Text("Add Channel or Contact") : Text("Add scanned Channel or Contact")
perfect :)

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +    // FIXME duplicate code from WelcomeLogIn.swift, maybe move to SwiftuiHelpers
Maybe add a new AlertPrompts.swift file containing all alert prompts from all SwiftUI files.

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                        errorAlert(title: Text("Error entering group chat"))
`Error entering Group/Channel`

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                    Text("Please make sure at least one account has connected before trying to add a contact or channel.")
not "has connected" but "is enabled"

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                    Text("Please make sure at least one account has connected before trying to add a contact or channel.")
"add a Contact or Group/Channel"

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                    Section(header: Text(verbatim: "Contact and Channel Jids are usually in the format: name@domain.tld")) {
Contacts or Group/Channel Jids are usually[...]"

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                        TextField("Contact or Channel Jid", text: $toAdd)
"Contact or Group/Channel Jid"

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                            scannedFingerprints == nil ? Text("Add Channel or Contact") : Text("Add scanned Channel or Contact")
Add "Group/Channel or Contact"

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +        .navigationBarTitle("Add Contact or Channel", displayMode: .inline)
likewise

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactsViewController.m
> +    if([[DataLayer sharedInstance] contactRequestsForAccount].count == 0) {
style (simply remove the {})

2022-11-12 23:24 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactsViewController.m
> +    [contactRequests setAction:@selector(openContactRequests:)];
the active chats view is missing a red dot for the button opening the contacts view controller, too.

2022-11-19 20:48 UTC, tmolitor-stud-tu commented
@janst97 friedrich told me you have commits not yet pushed. Could you push them please so that we can merge this PR in the next few days?

2022-11-20 13:37 UTC, janst97 commented on Monal/Classes/ContactRequestsMenu.swift
> +            Button {
Currently only the button size was increased, animation is still missing.

2022-11-20 13:38 UTC, janst97 commented on Monal/Classes/AddContactMenu.swift
> +                                Text("Clear scanned contact")
The idea was to highlight that the current option are only shown because the user scanned a contact.

2022-11-20 13:40 UTC, janst97 commented on Monal/Classes/ContactsViewController.m
> +    [contactRequests setAction:@selector(openContactRequests:)];
I added this with the last commit, however the red dot does not update after the user cleared all pending requests. I probably need either an event or a callback for that.

2022-11-20 15:41 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactsViewController.m
> +    [contactRequests setAction:@selector(openContactRequests:)];
You can use the kMonalContactRefresh event for that, I think that should work (the event will be triggered after one round-trip to the server)...

2022-11-20 15:42 UTC, tmolitor-stud-tu commented on Monal/Classes/AddContactMenu.swift
> +                                Text("Clear scanned contact")
We should use different texts for these two cases then: "Clear" for non-scanned inputs and "Clear scanned contact" for those scanned ones...

2022-11-20 15:43 UTC, tmolitor-stud-tu commented on Monal/Classes/ContactRequestsMenu.swift
> +            Button {
@FriedrichAltheide what do you mean by "animation"?

2022-11-20 15:44 UTC, tmolitor-stud-tu commented
I'll merge this, but please fix the open issues and create a new pull request for these!

2022-11-20 15:44 UTC, merged

2022-11-20 16:25 UTC, tmolitor-stud-tu commented
Please fix these build errors!
```
2022-11-20T16:23:24.8757070Z /Users/ci/Desktop/actions-runner/_work/Monal/Monal/Monal/Classes/AddContactMenu.swift:121:30: error: value of type 'TextField<Text>' has no member 'autocorrectionDisabled'
2022-11-20T16:23:24.8757330Z                             .autocorrectionDisabled()
2022-11-20T16:23:24.8757480Z                              ^~~~~~~~~~~~~~~~~~~~~~
2022-11-20T16:23:24.8757780Z /Users/ci/Desktop/actions-runner/_work/Monal/Monal/Monal/Classes/AddContactMenu.swift:122:50: error: cannot infer contextual base in reference to member 'none'
2022-11-20T16:23:24.8758020Z                             .autocapitalization(.none)
2022-11-20T16:23:24.8758170Z                                                 ~^~~~
2022-11-20T16:23:24.8758460Z /Users/ci/Desktop/actions-runner/_work/Monal/Monal/Monal/Classes/AddContactMenu.swift:124:76: error: cannot infer contextual base in reference to member 'secondary'
2022-11-20T16:23:24.8758750Z                             .foregroundColor(scannedFingerprints != nil ? .secondary : .primary)
2022-11-20T16:23:24.8758930Z                                                                           ~^~~~~~~~~
```

2022-11-20 16:28 UTC, tmolitor-stud-tu commented
Current code with this error is in branch `jan_stuff`

2022-11-20 18:29 UTC, janst97 commented
I can't reproduce this error, building works without problems for iOS and Catalyst with Xcode 14.1.

2022-11-20 18:39 UTC, tmolitor-stud-tu commented
@janst97 just push it to develop and try the ci build yourself...
the xcode on our CI is version 14.1, too

2022-11-20 18:40 UTC, tmolitor-stud-tu commented
@FriedrichAltheide any thoughts?

2022-11-23 17:51 UTC, FriedrichAltheide commented
fixed, installed newest Xcode version